/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MeEntity } from '../../models/me-entity';
import { UpdateMeDto } from '../../models/update-me-dto';

export interface AuthControllerUpdateMe$Params {
      body: UpdateMeDto
}

export function authControllerUpdateMe(http: HttpClient, rootUrl: string, params: AuthControllerUpdateMe$Params, context?: HttpContext): Observable<StrictHttpResponse<MeEntity>> {
  const rb = new RequestBuilder(rootUrl, authControllerUpdateMe.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MeEntity>;
    })
  );
}

authControllerUpdateMe.PATH = '/api/v1/auth/me';
