/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthResponseEntity } from '../../models/auth-response-entity';
import { ResetPasswordDto } from '../../models/reset-password-dto';

export interface AuthControllerResetPassword$Params {
      body: ResetPasswordDto
}

export function authControllerResetPassword(http: HttpClient, rootUrl: string, params: AuthControllerResetPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthResponseEntity>> {
  const rb = new RequestBuilder(rootUrl, authControllerResetPassword.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthResponseEntity>;
    })
  );
}

authControllerResetPassword.PATH = '/api/v1/auth/reset-password';
