FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY nest-cli.json tsconfig*.json prisma.config.ts ./
COPY libs/ libs/
COPY apps/api/ apps/api/

RUN npm ci --ignore-scripts

RUN npx prisma generate --schema apps/api/prisma/schema.prisma

# Script qui applique les migrations puis exécute le seed
COPY docker-migrate.sh /docker-migrate.sh
RUN chmod +x /docker-migrate.sh

CMD ["/bin/sh", "/docker-migrate.sh"]
