/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePolitiqueDto } from '../../models/create-politique-dto';
import { PolitiqueEntity } from '../../models/politique-entity';

export interface PolitiqueControllerCreate$Params {
      body: CreatePolitiqueDto
}

export function politiqueControllerCreate(http: HttpClient, rootUrl: string, params: PolitiqueControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<PolitiqueEntity>> {
  const rb = new RequestBuilder(rootUrl, politiqueControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PolitiqueEntity>;
    })
  );
}

politiqueControllerCreate.PATH = '/api/v1/politiques-gouvernance';
