/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PolitiqueEntity } from '../../models/politique-entity';
import { UpdatePolitiqueDto } from '../../models/update-politique-dto';

export interface PolitiqueControllerUpdate$Params {
  id: string;
      body: UpdatePolitiqueDto
}

export function politiqueControllerUpdate(http: HttpClient, rootUrl: string, params: PolitiqueControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<PolitiqueEntity>> {
  const rb = new RequestBuilder(rootUrl, politiqueControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PolitiqueEntity>;
    })
  );
}

politiqueControllerUpdate.PATH = '/api/v1/politiques-gouvernance/{id}';
