/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateDataAttributeDto } from '../../models/create-data-attribute-dto';
import { DataAttributeEntity } from '../../models/data-attribute-entity';

export interface DonneesControllerAddAttribute$Params {
  id: string;
      body: CreateDataAttributeDto
}

export function donneesControllerAddAttribute(http: HttpClient, rootUrl: string, params: DonneesControllerAddAttribute$Params, context?: HttpContext): Observable<StrictHttpResponse<DataAttributeEntity>> {
  const rb = new RequestBuilder(rootUrl, donneesControllerAddAttribute.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DataAttributeEntity>;
    })
  );
}

donneesControllerAddAttribute.PATH = '/api/v1/data-entities/{id}/attributs';
