/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DataEntityEntity } from '../../models/data-entity-entity';

export interface DonneesControllerFindOne$Params {
  id: string;
}

export function donneesControllerFindOne(http: HttpClient, rootUrl: string, params: DonneesControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<DataEntityEntity>> {
  const rb = new RequestBuilder(rootUrl, donneesControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DataEntityEntity>;
    })
  );
}

donneesControllerFindOne.PATH = '/api/v1/data-entities/{id}';
