/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateEchangeDto } from '../../models/create-echange-dto';
import { EchangeEntity } from '../../models/echange-entity';

export interface UrbanisationControllerCreateEchange$Params {
      body: CreateEchangeDto
}

export function urbanisationControllerCreateEchange(http: HttpClient, rootUrl: string, params: UrbanisationControllerCreateEchange$Params, context?: HttpContext): Observable<StrictHttpResponse<EchangeEntity>> {
  const rb = new RequestBuilder(rootUrl, urbanisationControllerCreateEchange.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EchangeEntity>;
    })
  );
}

urbanisationControllerCreateEchange.PATH = '/api/v1/applications-echanges';
