/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ZoneUrbanisationEntity } from '../../models/zone-urbanisation-entity';

export interface UrbanisationControllerFindAllZones$Params {
  type: string;
}

export function urbanisationControllerFindAllZones(http: HttpClient, rootUrl: string, params: UrbanisationControllerFindAllZones$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ZoneUrbanisationEntity>>> {
  const rb = new RequestBuilder(rootUrl, urbanisationControllerFindAllZones.PATH, 'get');
  if (params) {
    rb.query('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ZoneUrbanisationEntity>>;
    })
  );
}

urbanisationControllerFindAllZones.PATH = '/api/v1/zones-urbanisation';
