/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EchangeEntity } from '../../models/echange-entity';

export interface UrbanisationControllerFindAllEchanges$Params {
}

export function urbanisationControllerFindAllEchanges(http: HttpClient, rootUrl: string, params?: UrbanisationControllerFindAllEchanges$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EchangeEntity>>> {
  const rb = new RequestBuilder(rootUrl, urbanisationControllerFindAllEchanges.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EchangeEntity>>;
    })
  );
}

urbanisationControllerFindAllEchanges.PATH = '/api/v1/applications-echanges';
