/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ComponentsVueEntity } from '../../models/components-vue-entity';

export interface UrbanisationControllerGenerateComponentsVue$Params {
}

export function urbanisationControllerGenerateComponentsVue(http: HttpClient, rootUrl: string, params?: UrbanisationControllerGenerateComponentsVue$Params, context?: HttpContext): Observable<StrictHttpResponse<ComponentsVueEntity>> {
  const rb = new RequestBuilder(rootUrl, urbanisationControllerGenerateComponentsVue.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ComponentsVueEntity>;
    })
  );
}

urbanisationControllerGenerateComponentsVue.PATH = '/api/v1/applications/generate-vue';
