/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationEntity } from '../../models/application-entity';

export interface UrbanisationControllerFindOneApplication$Params {
  id: string;
}

export function urbanisationControllerFindOneApplication(http: HttpClient, rootUrl: string, params: UrbanisationControllerFindOneApplication$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationEntity>> {
  const rb = new RequestBuilder(rootUrl, urbanisationControllerFindOneApplication.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationEntity>;
    })
  );
}

urbanisationControllerFindOneApplication.PATH = '/api/v1/applications/{id}';
