/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationEntity } from '../../models/application-entity';
import { UpdateApplicationDto } from '../../models/update-application-dto';

export interface UrbanisationControllerUpdateApplication$Params {
  id: string;
      body: UpdateApplicationDto
}

export function urbanisationControllerUpdateApplication(http: HttpClient, rootUrl: string, params: UrbanisationControllerUpdateApplication$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationEntity>> {
  const rb = new RequestBuilder(rootUrl, urbanisationControllerUpdateApplication.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationEntity>;
    })
  );
}

urbanisationControllerUpdateApplication.PATH = '/api/v1/applications/{id}';
