/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateZoneDto } from '../../models/update-zone-dto';
import { ZoneUrbanisationEntity } from '../../models/zone-urbanisation-entity';

export interface UrbanisationControllerUpdateZone$Params {
  id: string;
      body: UpdateZoneDto
}

export function urbanisationControllerUpdateZone(http: HttpClient, rootUrl: string, params: UrbanisationControllerUpdateZone$Params, context?: HttpContext): Observable<StrictHttpResponse<ZoneUrbanisationEntity>> {
  const rb = new RequestBuilder(rootUrl, urbanisationControllerUpdateZone.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ZoneUrbanisationEntity>;
    })
  );
}

urbanisationControllerUpdateZone.PATH = '/api/v1/zones-urbanisation/{id}';
