/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UrbanisationControllerDesaffecter$Params {
  zoneId: string;
  applicationId: string;
}

export function urbanisationControllerDesaffecter(http: HttpClient, rootUrl: string, params: UrbanisationControllerDesaffecter$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, urbanisationControllerDesaffecter.PATH, 'delete');
  if (params) {
    rb.path('zoneId', params.zoneId, {});
    rb.path('applicationId', params.applicationId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

urbanisationControllerDesaffecter.PATH = '/api/v1/zones-urbanisation/{zoneId}/applications/{applicationId}';
