/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UrbanisationVueEntity } from '../../models/urbanisation-vue-entity';

export interface UrbanisationControllerGenerateVue$Params {
}

export function urbanisationControllerGenerateVue(http: HttpClient, rootUrl: string, params?: UrbanisationControllerGenerateVue$Params, context?: HttpContext): Observable<StrictHttpResponse<UrbanisationVueEntity>> {
  const rb = new RequestBuilder(rootUrl, urbanisationControllerGenerateVue.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UrbanisationVueEntity>;
    })
  );
}

urbanisationControllerGenerateVue.PATH = '/api/v1/zones-urbanisation/generate-vue';
