/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationEntity } from '../../models/application-entity';
import { CreateApplicationDto } from '../../models/create-application-dto';

export interface UrbanisationControllerCreateApplication$Params {
      body: CreateApplicationDto
}

export function urbanisationControllerCreateApplication(http: HttpClient, rootUrl: string, params: UrbanisationControllerCreateApplication$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationEntity>> {
  const rb = new RequestBuilder(rootUrl, urbanisationControllerCreateApplication.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationEntity>;
    })
  );
}

urbanisationControllerCreateApplication.PATH = '/api/v1/applications';
