/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AffectationEntity } from '../../models/affectation-entity';
import { AffecterApplicationDto } from '../../models/affecter-application-dto';

export interface UrbanisationControllerAffecter$Params {
      body: AffecterApplicationDto
}

export function urbanisationControllerAffecter(http: HttpClient, rootUrl: string, params: UrbanisationControllerAffecter$Params, context?: HttpContext): Observable<StrictHttpResponse<AffectationEntity>> {
  const rb = new RequestBuilder(rootUrl, urbanisationControllerAffecter.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AffectationEntity>;
    })
  );
}

urbanisationControllerAffecter.PATH = '/api/v1/zones-urbanisation/affecter';
