/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ZoneUrbanisationEntity } from '../../models/zone-urbanisation-entity';

export interface UrbanisationControllerFindOneZone$Params {
  id: string;
}

export function urbanisationControllerFindOneZone(http: HttpClient, rootUrl: string, params: UrbanisationControllerFindOneZone$Params, context?: HttpContext): Observable<StrictHttpResponse<ZoneUrbanisationEntity>> {
  const rb = new RequestBuilder(rootUrl, urbanisationControllerFindOneZone.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ZoneUrbanisationEntity>;
    })
  );
}

urbanisationControllerFindOneZone.PATH = '/api/v1/zones-urbanisation/{id}';
