/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateZoneDto } from '../../models/create-zone-dto';
import { ZoneUrbanisationEntity } from '../../models/zone-urbanisation-entity';

export interface UrbanisationControllerCreateZone$Params {
      body: CreateZoneDto
}

export function urbanisationControllerCreateZone(http: HttpClient, rootUrl: string, params: UrbanisationControllerCreateZone$Params, context?: HttpContext): Observable<StrictHttpResponse<ZoneUrbanisationEntity>> {
  const rb = new RequestBuilder(rootUrl, urbanisationControllerCreateZone.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ZoneUrbanisationEntity>;
    })
  );
}

urbanisationControllerCreateZone.PATH = '/api/v1/zones-urbanisation';
