/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ArchiApplicativeElementEntity } from '../../models/archi-applicative-element-entity';

export interface ArchitectureApplicativeControllerFindAllElements$Params {
}

export function architectureApplicativeControllerFindAllElements(http: HttpClient, rootUrl: string, params?: ArchitectureApplicativeControllerFindAllElements$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ArchiApplicativeElementEntity>>> {
  const rb = new RequestBuilder(rootUrl, architectureApplicativeControllerFindAllElements.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ArchiApplicativeElementEntity>>;
    })
  );
}

architectureApplicativeControllerFindAllElements.PATH = '/api/v1/architecture-applicative/elements';
