/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ArchitectureApplicativeVueEntity } from '../../models/architecture-applicative-vue-entity';

export interface ArchitectureApplicativeControllerGenerateVue$Params {
}

export function architectureApplicativeControllerGenerateVue(http: HttpClient, rootUrl: string, params?: ArchitectureApplicativeControllerGenerateVue$Params, context?: HttpContext): Observable<StrictHttpResponse<ArchitectureApplicativeVueEntity>> {
  const rb = new RequestBuilder(rootUrl, architectureApplicativeControllerGenerateVue.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ArchitectureApplicativeVueEntity>;
    })
  );
}

architectureApplicativeControllerGenerateVue.PATH = '/api/v1/architecture-applicative/generate-vue';
