/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ArchiApplicativeFluxEntity } from '../../models/archi-applicative-flux-entity';
import { CreateArchiApplicativeFluxDto } from '../../models/create-archi-applicative-flux-dto';

export interface ArchitectureApplicativeControllerCreateFlux$Params {
      body: CreateArchiApplicativeFluxDto
}

export function architectureApplicativeControllerCreateFlux(http: HttpClient, rootUrl: string, params: ArchitectureApplicativeControllerCreateFlux$Params, context?: HttpContext): Observable<StrictHttpResponse<ArchiApplicativeFluxEntity>> {
  const rb = new RequestBuilder(rootUrl, architectureApplicativeControllerCreateFlux.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ArchiApplicativeFluxEntity>;
    })
  );
}

architectureApplicativeControllerCreateFlux.PATH = '/api/v1/architecture-applicative/flux';
