/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DiagramLayoutResultEntity } from '../../models/diagram-layout-result-entity';

export interface ArchitectureApplicativeControllerGenerateLayout$Params {
}

export function architectureApplicativeControllerGenerateLayout(http: HttpClient, rootUrl: string, params?: ArchitectureApplicativeControllerGenerateLayout$Params, context?: HttpContext): Observable<StrictHttpResponse<DiagramLayoutResultEntity>> {
  const rb = new RequestBuilder(rootUrl, architectureApplicativeControllerGenerateLayout.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DiagramLayoutResultEntity>;
    })
  );
}

architectureApplicativeControllerGenerateLayout.PATH = '/api/v1/architecture-applicative/generate-layout';
