/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UploadLogoResultEntity } from '../../models/upload-logo-result-entity';

export interface UploadsControllerUploadLogo$Params {
      body: {
'file'?: Blob;
}
}

export function uploadsControllerUploadLogo(http: HttpClient, rootUrl: string, params: UploadsControllerUploadLogo$Params, context?: HttpContext): Observable<StrictHttpResponse<UploadLogoResultEntity>> {
  const rb = new RequestBuilder(rootUrl, uploadsControllerUploadLogo.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UploadLogoResultEntity>;
    })
  );
}

uploadsControllerUploadLogo.PATH = '/api/v1/uploads/logo';
