/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConformiteBySolutionEntity } from '../../models/conformite-by-solution-entity';
import { UpdateConformitesDto } from '../../models/update-conformites-dto';

export interface ConformiteControllerUpdate$Params {
  solutionId: string;
      body: UpdateConformitesDto
}

export function conformiteControllerUpdate(http: HttpClient, rootUrl: string, params: ConformiteControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ConformiteBySolutionEntity>>> {
  const rb = new RequestBuilder(rootUrl, conformiteControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('solutionId', params.solutionId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ConformiteBySolutionEntity>>;
    })
  );
}

conformiteControllerUpdate.PATH = '/api/v1/conformites-solutions/{solutionId}';
