/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConformiteBySolutionEntity } from '../../models/conformite-by-solution-entity';

export interface ConformiteControllerFindBySolution$Params {
  solutionId: string;
}

export function conformiteControllerFindBySolution(http: HttpClient, rootUrl: string, params: ConformiteControllerFindBySolution$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ConformiteBySolutionEntity>>> {
  const rb = new RequestBuilder(rootUrl, conformiteControllerFindBySolution.PATH, 'get');
  if (params) {
    rb.path('solutionId', params.solutionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ConformiteBySolutionEntity>>;
    })
  );
}

conformiteControllerFindBySolution.PATH = '/api/v1/conformites-solutions/{solutionId}';
