/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SolutionGapWithSolutionEntity } from '../../models/solution-gap-with-solution-entity';

export interface SolutionControllerListGaps$Params {
}

export function solutionControllerListGaps(http: HttpClient, rootUrl: string, params?: SolutionControllerListGaps$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SolutionGapWithSolutionEntity>>> {
  const rb = new RequestBuilder(rootUrl, solutionControllerListGaps.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SolutionGapWithSolutionEntity>>;
    })
  );
}

solutionControllerListGaps.PATH = '/api/v1/solutions/gaps';
