/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LinkGapsDto } from '../../models/link-gaps-dto';
import { SolutionEntity } from '../../models/solution-entity';

export interface SolutionControllerUpdateGaps$Params {
  id: string;
      body: LinkGapsDto
}

export function solutionControllerUpdateGaps(http: HttpClient, rootUrl: string, params: SolutionControllerUpdateGaps$Params, context?: HttpContext): Observable<StrictHttpResponse<SolutionEntity>> {
  const rb = new RequestBuilder(rootUrl, solutionControllerUpdateGaps.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SolutionEntity>;
    })
  );
}

solutionControllerUpdateGaps.PATH = '/api/v1/solutions/{id}/gaps';
