/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrganisationEntity } from '../../models/organisation-entity';

export interface OrganisationControllerFindMine$Params {
}

export function organisationControllerFindMine(http: HttpClient, rootUrl: string, params?: OrganisationControllerFindMine$Params, context?: HttpContext): Observable<StrictHttpResponse<OrganisationEntity>> {
  const rb = new RequestBuilder(rootUrl, organisationControllerFindMine.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrganisationEntity>;
    })
  );
}

organisationControllerFindMine.PATH = '/api/v1/organisations/me';
