/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrganisationExportEntity } from '../../models/organisation-export-entity';

export interface OrganisationControllerExportMine$Params {
}

export function organisationControllerExportMine(http: HttpClient, rootUrl: string, params?: OrganisationControllerExportMine$Params, context?: HttpContext): Observable<StrictHttpResponse<OrganisationExportEntity>> {
  const rb = new RequestBuilder(rootUrl, organisationControllerExportMine.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrganisationExportEntity>;
    })
  );
}

organisationControllerExportMine.PATH = '/api/v1/organisations/me/export';
