FROM node:20-alpine
WORKDIR /usr/src/app
COPY package.json package-lock.json* ./
RUN npm install --production
COPY . .
WORKDIR /usr/src/app/apps/api
RUN npm run build:api
EXPOSE 3000
CMD ["node", "dist/apps/api/main.js"]
