/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateVisionCanvasDto } from '../../models/update-vision-canvas-dto';
import { VisionCanvasEntity } from '../../models/vision-canvas-entity';

export interface VisionCanvasControllerUpdate$Params {
      body: UpdateVisionCanvasDto
}

export function visionCanvasControllerUpdate(http: HttpClient, rootUrl: string, params: VisionCanvasControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<VisionCanvasEntity>> {
  const rb = new RequestBuilder(rootUrl, visionCanvasControllerUpdate.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VisionCanvasEntity>;
    })
  );
}

visionCanvasControllerUpdate.PATH = '/api/v1/vision-canvas';
