/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VisionCanvasEntity } from '../../models/vision-canvas-entity';

export interface VisionCanvasControllerGet$Params {
}

export function visionCanvasControllerGet(http: HttpClient, rootUrl: string, params?: VisionCanvasControllerGet$Params, context?: HttpContext): Observable<StrictHttpResponse<VisionCanvasEntity>> {
  const rb = new RequestBuilder(rootUrl, visionCanvasControllerGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VisionCanvasEntity>;
    })
  );
}

visionCanvasControllerGet.PATH = '/api/v1/vision-canvas';
