/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ElementArchimateEntity } from '../../models/element-archimate-entity';
import { UpdatePositionDto } from '../../models/update-position-dto';

export interface ArchimateControllerUpdatePosition$Params {
  id: string;
      body: UpdatePositionDto
}

export function archimateControllerUpdatePosition(http: HttpClient, rootUrl: string, params: ArchimateControllerUpdatePosition$Params, context?: HttpContext): Observable<StrictHttpResponse<ElementArchimateEntity>> {
  const rb = new RequestBuilder(rootUrl, archimateControllerUpdatePosition.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ElementArchimateEntity>;
    })
  );
}

archimateControllerUpdatePosition.PATH = '/api/v1/elements-archimate/{id}/position';
