/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ElementArchimateEntity } from '../../models/element-archimate-entity';
import { UpdatePositionsBatchDto } from '../../models/update-positions-batch-dto';

export interface ArchimateControllerUpdatePositionsBatch$Params {
      body: UpdatePositionsBatchDto
}

export function archimateControllerUpdatePositionsBatch(http: HttpClient, rootUrl: string, params: ArchimateControllerUpdatePositionsBatch$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ElementArchimateEntity>>> {
  const rb = new RequestBuilder(rootUrl, archimateControllerUpdatePositionsBatch.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ElementArchimateEntity>>;
    })
  );
}

archimateControllerUpdatePositionsBatch.PATH = '/api/v1/elements-archimate/positions';
