/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ArchimateViewEntity } from '../../models/archimate-view-entity';

export interface ArchimateControllerGenerateVue$Params {
}

export function archimateControllerGenerateVue(http: HttpClient, rootUrl: string, params?: ArchimateControllerGenerateVue$Params, context?: HttpContext): Observable<StrictHttpResponse<ArchimateViewEntity>> {
  const rb = new RequestBuilder(rootUrl, archimateControllerGenerateVue.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ArchimateViewEntity>;
    })
  );
}

archimateControllerGenerateVue.PATH = '/api/v1/elements-archimate/generate-vue';
