/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateRelationDto } from '../../models/create-relation-dto';
import { RelationArchimateEntity } from '../../models/relation-archimate-entity';

export interface ArchimateControllerCreateRelation$Params {
      body: CreateRelationDto
}

export function archimateControllerCreateRelation(http: HttpClient, rootUrl: string, params: ArchimateControllerCreateRelation$Params, context?: HttpContext): Observable<StrictHttpResponse<RelationArchimateEntity>> {
  const rb = new RequestBuilder(rootUrl, archimateControllerCreateRelation.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RelationArchimateEntity>;
    })
  );
}

archimateControllerCreateRelation.PATH = '/api/v1/relations-archimate';
