/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CapaciteMetierEntity } from '../../models/capacite-metier-entity';
import { UpdateCapaciteDto } from '../../models/update-capacite-dto';

export interface ArchimateControllerUpdateCapacite$Params {
  id: string;
      body: UpdateCapaciteDto
}

export function archimateControllerUpdateCapacite(http: HttpClient, rootUrl: string, params: ArchimateControllerUpdateCapacite$Params, context?: HttpContext): Observable<StrictHttpResponse<CapaciteMetierEntity>> {
  const rb = new RequestBuilder(rootUrl, archimateControllerUpdateCapacite.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CapaciteMetierEntity>;
    })
  );
}

archimateControllerUpdateCapacite.PATH = '/api/v1/capacites-metier/{id}';
