/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ArchimateLayoutEntity } from '../../models/archimate-layout-entity';

export interface ArchimateControllerGenerateLayout$Params {
}

export function archimateControllerGenerateLayout(http: HttpClient, rootUrl: string, params?: ArchimateControllerGenerateLayout$Params, context?: HttpContext): Observable<StrictHttpResponse<ArchimateLayoutEntity>> {
  const rb = new RequestBuilder(rootUrl, archimateControllerGenerateLayout.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ArchimateLayoutEntity>;
    })
  );
}

archimateControllerGenerateLayout.PATH = '/api/v1/elements-archimate/generate-layout';
