/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ElementArchimateEntity } from '../../models/element-archimate-entity';

export interface ArchimateControllerFindAllElements$Params {

/**
 * Numéro de page, à partir de 1. Absent, la réponse n'est pas paginée (tableau complet).
 */
  page?: number;

/**
 * Nombre d'éléments par page, entre 1 et 200.
 */
  pageSize?: number;

/**
 * Filtre les éléments par type ArchiMate.
 */
  type?: 'VISION' | 'OBJECTIF_ARCHIMATE' | 'PRINCIPE' | 'EXIGENCE' | 'ACTEUR_METIER' | 'ROLE_METIER' | 'PROCESSUS_METIER' | 'SERVICE_METIER' | 'OBJET_METIER';
}

export function archimateControllerFindAllElements(http: HttpClient, rootUrl: string, params?: ArchimateControllerFindAllElements$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ElementArchimateEntity>>> {
  const rb = new RequestBuilder(rootUrl, archimateControllerFindAllElements.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ElementArchimateEntity>>;
    })
  );
}

archimateControllerFindAllElements.PATH = '/api/v1/elements-archimate';
