/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ElementArchimateEntity } from '../../models/element-archimate-entity';

export interface ArchimateControllerFindOneElement$Params {
  id: string;
}

export function archimateControllerFindOneElement(http: HttpClient, rootUrl: string, params: ArchimateControllerFindOneElement$Params, context?: HttpContext): Observable<StrictHttpResponse<ElementArchimateEntity>> {
  const rb = new RequestBuilder(rootUrl, archimateControllerFindOneElement.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ElementArchimateEntity>;
    })
  );
}

archimateControllerFindOneElement.PATH = '/api/v1/elements-archimate/{id}';
