/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePartiePrenanteDto } from '../../models/create-partie-prenante-dto';
import { PartiePrenanteEntity } from '../../models/partie-prenante-entity';

export interface PartiesPrenantesControllerCreate$Params {
      body: CreatePartiePrenanteDto
}

export function partiesPrenantesControllerCreate(http: HttpClient, rootUrl: string, params: PartiesPrenantesControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<PartiePrenanteEntity>> {
  const rb = new RequestBuilder(rootUrl, partiesPrenantesControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PartiePrenanteEntity>;
    })
  );
}

partiesPrenantesControllerCreate.PATH = '/api/v1/parties-prenantes';
