/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MembreEntity } from '../../models/membre-entity';
import { UpdateMembreDto } from '../../models/update-membre-dto';

export interface MembresControllerUpdate$Params {
  id: string;
      body: UpdateMembreDto
}

export function membresControllerUpdate(http: HttpClient, rootUrl: string, params: MembresControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<MembreEntity>> {
  const rb = new RequestBuilder(rootUrl, membresControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MembreEntity>;
    })
  );
}

membresControllerUpdate.PATH = '/api/v1/membres/{id}';
