/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateMembreDto } from '../../models/create-membre-dto';
import { MembreEntity } from '../../models/membre-entity';

export interface MembresControllerCreate$Params {
      body: CreateMembreDto
}

export function membresControllerCreate(http: HttpClient, rootUrl: string, params: MembresControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<MembreEntity>> {
  const rb = new RequestBuilder(rootUrl, membresControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MembreEntity>;
    })
  );
}

membresControllerCreate.PATH = '/api/v1/membres';
