/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EnqueteReponseEntity } from '../../models/enquete-reponse-entity';
import { ImportEnqueteDto } from '../../models/import-enquete-dto';

export interface EnqueteReponseControllerImport$Params {
      body: ImportEnqueteDto
}

export function enqueteReponseControllerImport(http: HttpClient, rootUrl: string, params: EnqueteReponseControllerImport$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EnqueteReponseEntity>>> {
  const rb = new RequestBuilder(rootUrl, enqueteReponseControllerImport.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EnqueteReponseEntity>>;
    })
  );
}

enqueteReponseControllerImport.PATH = '/api/v1/enquete-reponses/import';
