/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BpmnElementEntity } from '../../models/bpmn-element-entity';
import { UpdateBpmnElementDto } from '../../models/update-bpmn-element-dto';

export interface BpmnControllerUpdateElement$Params {
  elementId: string;
      body: UpdateBpmnElementDto
}

export function bpmnControllerUpdateElement(http: HttpClient, rootUrl: string, params: BpmnControllerUpdateElement$Params, context?: HttpContext): Observable<StrictHttpResponse<BpmnElementEntity>> {
  const rb = new RequestBuilder(rootUrl, bpmnControllerUpdateElement.PATH, 'patch');
  if (params) {
    rb.path('elementId', params.elementId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BpmnElementEntity>;
    })
  );
}

bpmnControllerUpdateElement.PATH = '/api/v1/bpmn-processus/elements/{elementId}';
