/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface BpmnControllerRemoveFlow$Params {
  flowId: string;
}

export function bpmnControllerRemoveFlow(http: HttpClient, rootUrl: string, params: BpmnControllerRemoveFlow$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, bpmnControllerRemoveFlow.PATH, 'delete');
  if (params) {
    rb.path('flowId', params.flowId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

bpmnControllerRemoveFlow.PATH = '/api/v1/bpmn-processus/flows/{flowId}';
