/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BpmnFlowEntity } from '../../models/bpmn-flow-entity';
import { CreateBpmnFlowDto } from '../../models/create-bpmn-flow-dto';

export interface BpmnControllerAddFlow$Params {
  id: string;
      body: CreateBpmnFlowDto
}

export function bpmnControllerAddFlow(http: HttpClient, rootUrl: string, params: BpmnControllerAddFlow$Params, context?: HttpContext): Observable<StrictHttpResponse<BpmnFlowEntity>> {
  const rb = new RequestBuilder(rootUrl, bpmnControllerAddFlow.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BpmnFlowEntity>;
    })
  );
}

bpmnControllerAddFlow.PATH = '/api/v1/bpmn-processus/{id}/flows';
