/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BpmnViewResultEntity } from '../../models/bpmn-view-result-entity';

export interface BpmnControllerGenerateVue$Params {
  id: string;
}

export function bpmnControllerGenerateVue(http: HttpClient, rootUrl: string, params: BpmnControllerGenerateVue$Params, context?: HttpContext): Observable<StrictHttpResponse<BpmnViewResultEntity>> {
  const rb = new RequestBuilder(rootUrl, bpmnControllerGenerateVue.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BpmnViewResultEntity>;
    })
  );
}

bpmnControllerGenerateVue.PATH = '/api/v1/bpmn-processus/{id}/generate-vue';
