/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BpmnProcessusDetailEntity } from '../../models/bpmn-processus-detail-entity';

export interface BpmnControllerFindOne$Params {
  id: string;
}

export function bpmnControllerFindOne(http: HttpClient, rootUrl: string, params: BpmnControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<BpmnProcessusDetailEntity>> {
  const rb = new RequestBuilder(rootUrl, bpmnControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BpmnProcessusDetailEntity>;
    })
  );
}

bpmnControllerFindOne.PATH = '/api/v1/bpmn-processus/{id}';
