/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BpmnProcessusEntity } from '../../models/bpmn-processus-entity';
import { CreateBpmnProcessusDto } from '../../models/create-bpmn-processus-dto';

export interface BpmnControllerCreate$Params {
      body: CreateBpmnProcessusDto
}

export function bpmnControllerCreate(http: HttpClient, rootUrl: string, params: BpmnControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<BpmnProcessusEntity>> {
  const rb = new RequestBuilder(rootUrl, bpmnControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BpmnProcessusEntity>;
    })
  );
}

bpmnControllerCreate.PATH = '/api/v1/bpmn-processus';
