/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BpmnElementEntity } from '../../models/bpmn-element-entity';
import { CreateBpmnElementDto } from '../../models/create-bpmn-element-dto';

export interface BpmnControllerAddElement$Params {
  id: string;
      body: CreateBpmnElementDto
}

export function bpmnControllerAddElement(http: HttpClient, rootUrl: string, params: BpmnControllerAddElement$Params, context?: HttpContext): Observable<StrictHttpResponse<BpmnElementEntity>> {
  const rb = new RequestBuilder(rootUrl, bpmnControllerAddElement.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BpmnElementEntity>;
    })
  );
}

bpmnControllerAddElement.PATH = '/api/v1/bpmn-processus/{id}/elements';
