/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BpmnProcessusEntity } from '../../models/bpmn-processus-entity';
import { UpdateBpmnProcessusDto } from '../../models/update-bpmn-processus-dto';

export interface BpmnControllerUpdate$Params {
  id: string;
      body: UpdateBpmnProcessusDto
}

export function bpmnControllerUpdate(http: HttpClient, rootUrl: string, params: BpmnControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<BpmnProcessusEntity>> {
  const rb = new RequestBuilder(rootUrl, bpmnControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BpmnProcessusEntity>;
    })
  );
}

bpmnControllerUpdate.PATH = '/api/v1/bpmn-processus/{id}';
