/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ServiceEntity } from '../../models/service-entity';

export interface ServiceControllerFindOne$Params {
  id: string;
}

export function serviceControllerFindOne(http: HttpClient, rootUrl: string, params: ServiceControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<ServiceEntity>> {
  const rb = new RequestBuilder(rootUrl, serviceControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ServiceEntity>;
    })
  );
}

serviceControllerFindOne.PATH = '/api/v1/services/{id}';
