/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ServiceEntity } from '../../models/service-entity';
import { UpdateServiceDto } from '../../models/update-service-dto';

export interface ServiceControllerUpdate$Params {
  id: string;
      body: UpdateServiceDto
}

export function serviceControllerUpdate(http: HttpClient, rootUrl: string, params: ServiceControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ServiceEntity>> {
  const rb = new RequestBuilder(rootUrl, serviceControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ServiceEntity>;
    })
  );
}

serviceControllerUpdate.PATH = '/api/v1/services/{id}';
