/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ServiceViewEntity } from '../../models/service-view-entity';

export interface ServiceControllerGenerateVue$Params {
}

export function serviceControllerGenerateVue(http: HttpClient, rootUrl: string, params?: ServiceControllerGenerateVue$Params, context?: HttpContext): Observable<StrictHttpResponse<ServiceViewEntity>> {
  const rb = new RequestBuilder(rootUrl, serviceControllerGenerateVue.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ServiceViewEntity>;
    })
  );
}

serviceControllerGenerateVue.PATH = '/api/v1/services/generate-vue';
