/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTechComponentDto } from '../../models/create-tech-component-dto';
import { TechComponentEntity } from '../../models/tech-component-entity';

export interface TechnologieControllerCreate$Params {
      body: CreateTechComponentDto
}

export function technologieControllerCreate(http: HttpClient, rootUrl: string, params: TechnologieControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<TechComponentEntity>> {
  const rb = new RequestBuilder(rootUrl, technologieControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TechComponentEntity>;
    })
  );
}

technologieControllerCreate.PATH = '/api/v1/tech-components';
