/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TechComponentEntity } from '../../models/tech-component-entity';
import { UpdateTechComponentDto } from '../../models/update-tech-component-dto';

export interface TechnologieControllerUpdate$Params {
  id: string;
      body: UpdateTechComponentDto
}

export function technologieControllerUpdate(http: HttpClient, rootUrl: string, params: TechnologieControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<TechComponentEntity>> {
  const rb = new RequestBuilder(rootUrl, technologieControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TechComponentEntity>;
    })
  );
}

technologieControllerUpdate.PATH = '/api/v1/tech-components/{id}';
