/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeployerApplicationDto } from '../../models/deployer-application-dto';
import { TechDeploiementEntity } from '../../models/tech-deploiement-entity';

export interface TechnologieControllerDeployer$Params {
      body: DeployerApplicationDto
}

export function technologieControllerDeployer(http: HttpClient, rootUrl: string, params: TechnologieControllerDeployer$Params, context?: HttpContext): Observable<StrictHttpResponse<TechDeploiementEntity>> {
  const rb = new RequestBuilder(rootUrl, technologieControllerDeployer.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TechDeploiementEntity>;
    })
  );
}

technologieControllerDeployer.PATH = '/api/v1/tech-components/deployer';
