/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateChangementDto } from '../../models/create-changement-dto';
import { DemandeChangementEntity } from '../../models/demande-changement-entity';

export interface ChangementControllerCreate$Params {
      body: CreateChangementDto
}

export function changementControllerCreate(http: HttpClient, rootUrl: string, params: ChangementControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<DemandeChangementEntity>> {
  const rb = new RequestBuilder(rootUrl, changementControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DemandeChangementEntity>;
    })
  );
}

changementControllerCreate.PATH = '/api/v1/demandes-changement';
