/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DemandeChangementEntity } from '../../models/demande-changement-entity';

export interface ChangementControllerFindAll$Params {

/**
 * Numéro de page, à partir de 1. Absent, la réponse n'est pas paginée (tableau complet).
 */
  page?: number;

/**
 * Nombre d'éléments par page, entre 1 et 200.
 */
  pageSize?: number;
}

export function changementControllerFindAll(http: HttpClient, rootUrl: string, params?: ChangementControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DemandeChangementEntity>>> {
  const rb = new RequestBuilder(rootUrl, changementControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DemandeChangementEntity>>;
    })
  );
}

changementControllerFindAll.PATH = '/api/v1/demandes-changement';
