/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DemandeChangementEntity } from '../../models/demande-changement-entity';
import { UpdateChangementDto } from '../../models/update-changement-dto';

export interface ChangementControllerUpdate$Params {
  id: string;
      body: UpdateChangementDto
}

export function changementControllerUpdate(http: HttpClient, rootUrl: string, params: ChangementControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<DemandeChangementEntity>> {
  const rb = new RequestBuilder(rootUrl, changementControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DemandeChangementEntity>;
    })
  );
}

changementControllerUpdate.PATH = '/api/v1/demandes-changement/{id}';
