/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjetEntity } from '../../models/projet-entity';

export interface RoadmapControllerFindOne$Params {
  id: string;
}

export function roadmapControllerFindOne(http: HttpClient, rootUrl: string, params: RoadmapControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjetEntity>> {
  const rb = new RequestBuilder(rootUrl, roadmapControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjetEntity>;
    })
  );
}

roadmapControllerFindOne.PATH = '/api/v1/projets/{id}';
