/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjetEntity } from '../../models/projet-entity';
import { UpdateProjetDto } from '../../models/update-projet-dto';

export interface RoadmapControllerUpdate$Params {
  id: string;
      body: UpdateProjetDto
}

export function roadmapControllerUpdate(http: HttpClient, rootUrl: string, params: RoadmapControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjetEntity>> {
  const rb = new RequestBuilder(rootUrl, roadmapControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjetEntity>;
    })
  );
}

roadmapControllerUpdate.PATH = '/api/v1/projets/{id}';
