/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateInvitationDto } from '../../models/create-invitation-dto';
import { InvitationEntity } from '../../models/invitation-entity';

export interface InvitationControllerCreate$Params {
      body: CreateInvitationDto
}

export function invitationControllerCreate(http: HttpClient, rootUrl: string, params: InvitationControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<InvitationEntity>> {
  const rb = new RequestBuilder(rootUrl, invitationControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvitationEntity>;
    })
  );
}

invitationControllerCreate.PATH = '/api/v1/invitations';
