/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvitationPublicEntity } from '../../models/invitation-public-entity';

export interface InvitationPublicControllerFindByToken$Params {
  token: string;
}

export function invitationPublicControllerFindByToken(http: HttpClient, rootUrl: string, params: InvitationPublicControllerFindByToken$Params, context?: HttpContext): Observable<StrictHttpResponse<InvitationPublicEntity>> {
  const rb = new RequestBuilder(rootUrl, invitationPublicControllerFindByToken.PATH, 'get');
  if (params) {
    rb.path('token', params.token, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvitationPublicEntity>;
    })
  );
}

invitationPublicControllerFindByToken.PATH = '/api/v1/invitations/token/{token}';
