/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AcceptInvitationDto } from '../../models/accept-invitation-dto';
import { AuthResponseEntity } from '../../models/auth-response-entity';

export interface InvitationPublicControllerAccept$Params {
      body: AcceptInvitationDto
}

export function invitationPublicControllerAccept(http: HttpClient, rootUrl: string, params: InvitationPublicControllerAccept$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthResponseEntity>> {
  const rb = new RequestBuilder(rootUrl, invitationPublicControllerAccept.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthResponseEntity>;
    })
  );
}

invitationPublicControllerAccept.PATH = '/api/v1/invitations/accept';
