/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CanevasRelationEntity } from '../../models/canevas-relation-entity';
import { CreateCanevasRelationDto } from '../../models/create-canevas-relation-dto';

export interface CanevasControllerCreate$Params {
      body: CreateCanevasRelationDto
}

export function canevasControllerCreate(http: HttpClient, rootUrl: string, params: CanevasControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<CanevasRelationEntity>> {
  const rb = new RequestBuilder(rootUrl, canevasControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CanevasRelationEntity>;
    })
  );
}

canevasControllerCreate.PATH = '/api/v1/canevas-relations';
