/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminOrganisationEntity } from '../../models/admin-organisation-entity';

export interface AdminControllerGetOrganisation$Params {
  id: string;
}

export function adminControllerGetOrganisation(http: HttpClient, rootUrl: string, params: AdminControllerGetOrganisation$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminOrganisationEntity>> {
  const rb = new RequestBuilder(rootUrl, adminControllerGetOrganisation.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminOrganisationEntity>;
    })
  );
}

adminControllerGetOrganisation.PATH = '/api/v1/admin/organisations/{id}';
