/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminStatsEntity } from '../../models/admin-stats-entity';

export interface AdminControllerStats$Params {
}

export function adminControllerStats(http: HttpClient, rootUrl: string, params?: AdminControllerStats$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminStatsEntity>> {
  const rb = new RequestBuilder(rootUrl, adminControllerStats.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminStatsEntity>;
    })
  );
}

adminControllerStats.PATH = '/api/v1/admin/stats';
