/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminOrganisationListItemEntity } from '../../models/admin-organisation-list-item-entity';

export interface AdminControllerListOrganisations$Params {

/**
 * Numéro de page, à partir de 1. Absent, la réponse n'est pas paginée (tableau complet).
 */
  page?: number;

/**
 * Nombre d'éléments par page, entre 1 et 200.
 */
  pageSize?: number;

/**
 * Filtre les organisations par statut.
 */
  statut?: 'EN_ATTENTE' | 'VALIDEE' | 'REJETEE';
}

export function adminControllerListOrganisations(http: HttpClient, rootUrl: string, params?: AdminControllerListOrganisations$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AdminOrganisationListItemEntity>>> {
  const rb = new RequestBuilder(rootUrl, adminControllerListOrganisations.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('statut', params.statut, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AdminOrganisationListItemEntity>>;
    })
  );
}

adminControllerListOrganisations.PATH = '/api/v1/admin/organisations';
