/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminOrganisationActionResultEntity } from '../../models/admin-organisation-action-result-entity';

export interface AdminControllerValider$Params {
  id: string;
}

export function adminControllerValider(http: HttpClient, rootUrl: string, params: AdminControllerValider$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminOrganisationActionResultEntity>> {
  const rb = new RequestBuilder(rootUrl, adminControllerValider.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminOrganisationActionResultEntity>;
    })
  );
}

adminControllerValider.PATH = '/api/v1/admin/organisations/{id}/valider';
