/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ObjectifEntity } from '../../models/objectif-entity';

export interface ObjectifControllerFindOne$Params {
  id: string;
}

export function objectifControllerFindOne(http: HttpClient, rootUrl: string, params: ObjectifControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectifEntity>> {
  const rb = new RequestBuilder(rootUrl, objectifControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ObjectifEntity>;
    })
  );
}

objectifControllerFindOne.PATH = '/api/v1/objectifs/{id}';
