/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ObjectifEntity } from '../../models/objectif-entity';
import { UpdateObjectifDto } from '../../models/update-objectif-dto';

export interface ObjectifControllerUpdate$Params {
  id: string;
      body: UpdateObjectifDto
}

export function objectifControllerUpdate(http: HttpClient, rootUrl: string, params: ObjectifControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectifEntity>> {
  const rb = new RequestBuilder(rootUrl, objectifControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ObjectifEntity>;
    })
  );
}

objectifControllerUpdate.PATH = '/api/v1/objectifs/{id}';
