/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateObjectifDto } from '../../models/create-objectif-dto';
import { ObjectifEntity } from '../../models/objectif-entity';

export interface ObjectifControllerCreate$Params {
      body: CreateObjectifDto
}

export function objectifControllerCreate(http: HttpClient, rootUrl: string, params: ObjectifControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectifEntity>> {
  const rb = new RequestBuilder(rootUrl, objectifControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ObjectifEntity>;
    })
  );
}

objectifControllerCreate.PATH = '/api/v1/objectifs';
