/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AcceptInvitationDto {

  /**
   * Nom complet du nouveau membre.
   */
  nom: string;

  /**
   * Mot de passe choisi, 8 caractères minimum.
   */
  password: string;

  /**
   * Jeton reçu dans le lien d'invitation.
   */
  token: string;
}
