/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActeurItemDto {

  /**
   * Nom de l'acteur.
   */
  nom: string;

  /**
   * Type de l'acteur, limité à ACTEUR_METIER ou ROLE_METIER.
   */
  type: 'VISION' | 'OBJECTIF_ARCHIMATE' | 'PRINCIPE' | 'EXIGENCE' | 'ACTEUR_METIER' | 'ROLE_METIER' | 'PROCESSUS_METIER' | 'SERVICE_METIER' | 'OBJET_METIER';
}
