/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrganisationUsersCountEntity } from '../models/organisation-users-count-entity';
export interface AdminOrganisationListItemEntity {

  /**
   * Compteur d'utilisateurs de cette organisation.
   */
  '_count': OrganisationUsersCountEntity;

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Identifiant de l'organisation.
   */
  id: string;

  /**
   * Nom de l'organisation.
   */
  nom: string;

  /**
   * Pays.
   */
  pays?: string | null;

  /**
   * Secteur d'activité.
   */
  secteur?: string | null;

  /**
   * Statut de validation de l'organisation.
   */
  statut: 'EN_ATTENTE' | 'VALIDEE' | 'REJETEE';

  /**
   * Taille de l'organisation.
   */
  taille?: string | null;

  /**
   * Date de validation par le superadmin.
   */
  validatedAt?: string | null;

  /**
   * Ville du siège social.
   */
  ville?: string | null;
}
