/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminUtilisateurOrganisationRefEntity } from '../models/admin-utilisateur-organisation-ref-entity';
export interface AdminUtilisateurEntity {

  /**
   * Date de création du compte.
   */
  createdAt: string;

  /**
   * Adresse e-mail de l'utilisateur.
   */
  email: string;

  /**
   * Identifiant de l'utilisateur.
   */
  id: string;

  /**
   * Nom de l'utilisateur.
   */
  nom: string;

  /**
   * Organisation de rattachement de l'utilisateur.
   */
  organisation?: (AdminUtilisateurOrganisationRefEntity & {
}) | null;

  /**
   * Rôle de l'utilisateur.
   */
  role: 'SUPERADMIN' | 'ADMINISTRATEUR' | 'ARCHITECTE';
}
