/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminUtilisateurOrganisationRefEntity {

  /**
   * Identifiant de l'organisation.
   */
  id: string;

  /**
   * Nom de l'organisation.
   */
  nom: string;
}
