/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminStatsOrganisationsEntity } from '../models/admin-stats-organisations-entity';
export interface AdminStatsEntity {

  /**
   * Répartition des organisations par statut.
   */
  organisations: AdminStatsOrganisationsEntity;

  /**
   * Nombre total d'utilisateurs, hors comptes superadmin.
   */
  totalUtilisateurs: number;
}
