/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminStatsOrganisationsEntity {

  /**
   * Nombre d'organisations en attente de validation.
   */
  enAttente: number;

  /**
   * Nombre d'organisations rejetées.
   */
  rejetees: number;

  /**
   * Nombre total d'organisations, tous statuts confondus.
   */
  total: number;

  /**
   * Nombre d'organisations validées.
   */
  validees: number;
}
