/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AffectationApplicationRefEntity } from '../models/affectation-application-ref-entity';
import { AffectationZoneRefEntity } from '../models/affectation-zone-ref-entity';
export interface AffectationEntity {

  /**
   * Application affectée.
   */
  application: AffectationApplicationRefEntity;

  /**
   * Identifiant de l'application affectée.
   */
  applicationId: string;

  /**
   * Zone (îlot) affectée.
   */
  zone: AffectationZoneRefEntity;

  /**
   * Identifiant de la zone (îlot) affectée.
   */
  zoneId: string;
}
