/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AffecterApplicationDto {

  /**
   * Identifiant de l'application à affecter.
   */
  applicationId: string;

  /**
   * Identifiant de la zone d'urbanisation cible.
   */
  zoneId: string;
}
