/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AffectationApplicationRefEntity {

  /**
   * Identifiant de l'application.
   */
  id: string;

  /**
   * Nom de l'application.
   */
  nom: string;
}
