/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationEchangeRefEntity } from '../models/application-echange-ref-entity';
export interface ApplicationEchangeAsSourceEntity {

  /**
   * Date de création de l'échange.
   */
  createdAt: string;

  /**
   * Description de l'échange.
   */
  description?: string | null;

  /**
   * Identifiant de l'échange.
   */
  id: string;

  /**
   * Protocole utilisé pour l'échange.
   */
  protocole?: string | null;

  /**
   * Identifiant de l'application source.
   */
  sourceId: string;

  /**
   * Application cible de l'échange.
   */
  target: ApplicationEchangeRefEntity;

  /**
   * Identifiant de l'application cible.
   */
  targetId: string;
}
