/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicationCountEntity {

  /**
   * Nombre d'échanges où l'application est source.
   */
  echangesSource: number;

  /**
   * Nombre d'échanges où l'application est cible.
   */
  echangesTarget: number;

  /**
   * Nombre de services applicatifs de l'application.
   */
  services: number;

  /**
   * Nombre de zones d'urbanisation auxquelles l'application est affectée.
   */
  zones: number;
}
