/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationZoneRefEntity } from '../models/application-zone-ref-entity';
export interface ApplicationZoneEntity {

  /**
   * Identifiant de l'application.
   */
  applicationId: string;

  /**
   * Zone affectée.
   */
  zone: ApplicationZoneRefEntity;

  /**
   * Identifiant de la zone.
   */
  zoneId: string;
}
