/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicationServiceEntity {

  /**
   * Identifiant de l'application propriétaire du service.
   */
  applicationId: string;

  /**
   * Description du service applicatif.
   */
  description?: string | null;

  /**
   * Identifiant du service applicatif.
   */
  id: string;

  /**
   * Nom du service applicatif.
   */
  nom: string;
}
