/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationCountEntity } from '../models/application-count-entity';
import { ApplicationEchangeAsSourceEntity } from '../models/application-echange-as-source-entity';
import { ApplicationEchangeAsTargetEntity } from '../models/application-echange-as-target-entity';
import { ApplicationServiceEntity } from '../models/application-service-entity';
import { ApplicationZoneEntity } from '../models/application-zone-entity';
export interface ApplicationEntity {

  /**
   * Compteurs des relations de l'application.
   */
  '_count'?: ApplicationCountEntity;

  /**
   * Date de création de l'application.
   */
  createdAt: string;

  /**
   * Description de l'application.
   */
  description?: string | null;

  /**
   * Échanges applicatifs dans lesquels l'application est source.
   */
  echangesSource?: Array<ApplicationEchangeAsSourceEntity>;

  /**
   * Échanges applicatifs dans lesquels l'application est cible.
   */
  echangesTarget?: Array<ApplicationEchangeAsTargetEntity>;

  /**
   * Identifiant de l'application.
   */
  id: string;

  /**
   * Nom de l'application.
   */
  nom: string;

  /**
   * Identifiant de l'organisation propriétaire de l'application.
   */
  organisationId: string;

  /**
   * Position horizontale de l'application sur le canevas.
   */
  positionX?: number | null;

  /**
   * Position verticale de l'application sur le canevas.
   */
  positionY?: number | null;

  /**
   * Services applicatifs de l'application.
   */
  services?: Array<ApplicationServiceEntity>;

  /**
   * Statut de l'application (AS_IS, TO_BE ou LES_DEUX).
   */
  statut: 'AS_IS' | 'TO_BE' | 'LES_DEUX';

  /**
   * Date de dernière modification de l'application.
   */
  updatedAt: string;

  /**
   * Zones d'urbanisation auxquelles l'application est affectée.
   */
  zones?: Array<ApplicationZoneEntity>;
}
