/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicationItemDto {

  /**
   * Description de l'application.
   */
  description?: string;

  /**
   * Nom de l'application.
   */
  nom: string;
}
