/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicationZoneRefEntity {

  /**
   * Identifiant de la zone.
   */
  id: string;

  /**
   * Nom de la zone.
   */
  nom: string;

  /**
   * Type de la zone.
   */
  type: 'ZONE' | 'QUARTIER' | 'ILOT';
}
