/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ArchiApplicativeElementEntity } from '../models/archi-applicative-element-entity';
export interface ArchiApplicativeFluxWithElementsEntity {

  /**
   * Date de création du flux.
   */
  createdAt: string;

  /**
   * Identifiant du flux.
   */
  id: string;

  /**
   * Libellé affiché sur le flux.
   */
  label?: string | null;

  /**
   * Élément source du flux.
   */
  source: ArchiApplicativeElementEntity;

  /**
   * Identifiant de l'élément source du flux.
   */
  sourceId: string;

  /**
   * Élément cible du flux.
   */
  target: ArchiApplicativeElementEntity;

  /**
   * Identifiant de l'élément cible du flux.
   */
  targetId: string;

  /**
   * Type du flux entre les deux éléments.
   */
  type: 'API' | 'DONNEES' | 'AUTHENTIFICATION' | 'RESEAU';
}
