/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArchiApplicativeElementEntity {

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Description détaillée de l'élément.
   */
  description?: string | null;

  /**
   * Identifiant de l'élément d'architecture applicative.
   */
  id: string;

  /**
   * Nom de l'élément d'architecture applicative.
   */
  nom: string;

  /**
   * Identifiant de l'organisation propriétaire.
   */
  organisationId: string;

  /**
   * Position horizontale sur le canevas.
   */
  positionX?: number | null;

  /**
   * Position verticale sur le canevas.
   */
  positionY?: number | null;

  /**
   * Type de l'élément d'architecture applicative.
   */
  type: 'APPLICATION' | 'UTILISATEUR_INTERNE' | 'UTILISATEUR_EXTERNE' | 'SYSTEME_EXTERNE' | 'BASE_DE_DONNEES' | 'INFRASTRUCTURE' | 'SECURITE';

  /**
   * Date de dernière modification.
   */
  updatedAt: string;
}
