/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArchimateViewEntity {

  /**
   * Nombre d'éléments représentés dans la vue.
   */
  elementCount: number;

  /**
   * Nombre de relations représentées dans la vue.
   */
  relationCount: number;

  /**
   * Contenu SVG de la vue ArchiMate générée.
   */
  svg: string;
}
