/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArchitectureApplicativeVueEntity {

  /**
   * Nombre d'éléments représentés dans la vue.
   */
  elementCount: number;

  /**
   * Nombre de flux représentés dans la vue.
   */
  fluxCount: number;

  /**
   * Contenu SVG de la vue d'architecture applicative générée.
   */
  svg: string;
}
