/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ElementArchimateEntity } from '../models/element-archimate-entity';
export interface ArchimateLayoutEntity {

  /**
   * Nombre d'éléments repositionnés.
   */
  elementCount: number;

  /**
   * Éléments ArchiMate mis à jour avec leurs nouvelles positions.
   */
  elements: Array<ElementArchimateEntity>;
}
