/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthOrganisationEntity {

  /**
   * Identifiant de l'organisation.
   */
  id: string;

  /**
   * Nom de l'organisation.
   */
  nom: string;

  /**
   * Statut de validation de l'organisation.
   */
  statut: 'EN_ATTENTE' | 'VALIDEE' | 'REJETEE';
}
