/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthUserEntity } from '../models/auth-user-entity';
export interface AuthResponseEntity {

  /**
   * Jeton JWT d'accès, également posé en cookie.
   */
  accessToken: string;

  /**
   * Profil utilisateur authentifié.
   */
  user: AuthUserEntity;
}
