/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BpmnFlowEntity {

  /**
   * Identifiant du flux BPMN.
   */
  id: string;

  /**
   * Libellé affiché sur le flux.
   */
  label?: string | null;

  /**
   * Identifiant de l'élément source.
   */
  sourceId: string;

  /**
   * Identifiant de l'élément cible.
   */
  targetId: string;
}
