/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BpmnProcessusItemDto {

  /**
   * Description du processus BPMN.
   */
  description?: string;

  /**
   * Nom du processus BPMN.
   */
  nom: string;
}
