/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BpmnProcessusCountEntity } from '../models/bpmn-processus-count-entity';
export interface BpmnProcessusListItemEntity {

  /**
   * Compteurs des relations du processus.
   */
  '_count': BpmnProcessusCountEntity;

  /**
   * Source XML bpmn-js du diagramme.
   */
  bpmnXml?: string | null;

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Description du processus.
   */
  description?: string | null;

  /**
   * Identifiant du processus BPMN.
   */
  id: string;

  /**
   * Nom du processus.
   */
  nom: string;

  /**
   * Identifiant de l'organisation propriétaire.
   */
  organisationId: string;

  /**
   * Classification du processus dans la cartographie (métier, support ou pilotage).
   */
  type: 'METIER' | 'SUPPORT' | 'PILOTAGE';

  /**
   * Date de dernière mise à jour.
   */
  updatedAt: string;
}
