/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BpmnProcessusCountEntity {

  /**
   * Nombre d'éléments rattachés au processus.
   */
  elements: number;
}
