/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BpmnFlowEntity } from '../models/bpmn-flow-entity';
export interface BpmnElementWithFlowsEntity {

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Déclencheur de l'événement, pertinent uniquement pour un type événement.
   */
  declencheur?: ('MESSAGE' | 'MINUTERIE' | 'ERREUR' | 'SIGNAL' | 'CONDITIONNEL' | 'TERMINAISON' | 'ESCALADE') | null;

  /**
   * Flux dont cet élément est la source.
   */
  flowsSource: Array<BpmnFlowEntity>;

  /**
   * Flux dont cet élément est la cible.
   */
  flowsTarget: Array<BpmnFlowEntity>;

  /**
   * Identifiant de l'élément BPMN.
   */
  id: string;

  /**
   * Nom de l'élément.
   */
  nom: string;

  /**
   * Position horizontale enregistrée dans l'éditeur.
   */
  positionX?: number | null;

  /**
   * Position verticale enregistrée dans l'éditeur.
   */
  positionY?: number | null;

  /**
   * Identifiant du processus BPMN parent.
   */
  processusId: string;

  /**
   * Statut de l'élément dans la cartographie AS_IS / TO_BE.
   */
  statut: 'AS_IS' | 'TO_BE' | 'LES_DEUX';

  /**
   * Type de l'élément BPMN.
   */
  type: 'EVENEMENT_DEBUT' | 'EVENEMENT_FIN' | 'EVENEMENT_INTERMEDIAIRE' | 'TACHE' | 'PASSERELLE_EXCLUSIVE' | 'PASSERELLE_PARALLELE' | 'PASSERELLE_INCLUSIVE' | 'PASSERELLE_EVENEMENTIELLE' | 'SOUS_PROCESSUS';

  /**
   * Nature de la tâche, pertinente uniquement pour le type TACHE.
   */
  typeTache?: ('UTILISATEUR' | 'SERVICE' | 'MANUELLE' | 'ENVOI' | 'RECEPTION' | 'REGLE_METIER' | 'SCRIPT') | null;
}
