/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CanevasRelationEntity {

  /**
   * Date de création de la relation.
   */
  createdAt: string;

  /**
   * Identifiant de la relation du canevas.
   */
  id: string;

  /**
   * Annotation libre (ex. type de lien réseau pour le diagramme de déploiement).
   */
  label?: string | null;

  /**
   * Identifiant de l'organisation propriétaire.
   */
  organisationId: string;

  /**
   * Identifiant de l'élément source.
   */
  sourceId: string;

  /**
   * Nature de l'élément source (type de brique du canevas).
   */
  sourceKind: 'ARCHIMATE' | 'APPLICATION' | 'TECH_COMPONENT' | 'DATA_ENTITY';

  /**
   * Identifiant de l'élément cible.
   */
  targetId: string;

  /**
   * Nature de l'élément cible (type de brique du canevas).
   */
  targetKind: 'ARCHIMATE' | 'APPLICATION' | 'TECH_COMPONENT' | 'DATA_ENTITY';

  /**
   * Type de relation entre les deux éléments du canevas.
   */
  type: 'ASSIGNATION' | 'COMPOSITION' | 'REALISATION' | 'ASSOCIATION';
}
