/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ElementArchimateEntity } from '../models/element-archimate-entity';
import { ElementCountEntity } from '../models/element-count-entity';
export interface CapaciteMetierEntity {

  /**
   * Compteur des éléments rattachés à cette capacité.
   */
  '_count'?: ElementCountEntity;

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Description de la capacité métier.
   */
  description?: string | null;

  /**
   * Éléments ArchiMate rattachés à cette capacité, triés par nom.
   */
  elements?: Array<ElementArchimateEntity>;

  /**
   * Identifiant de la capacité métier.
   */
  id: string;

  /**
   * Nom de la capacité métier.
   */
  nom: string;

  /**
   * Identifiant de l'organisation propriétaire.
   */
  organisationId: string;

  /**
   * Date de dernière modification.
   */
  updatedAt: string;
}
