/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CapaciteRefEntity {

  /**
   * Identifiant de la capacité métier.
   */
  id: string;

  /**
   * Nom de la capacité métier.
   */
  nom: string;
}
