/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CapaciteItemDto {

  /**
   * Description de la capacité métier.
   */
  description?: string;

  /**
   * Nom de la capacité métier.
   */
  nom: string;
}
