/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChangementStatsEntity {

  /**
   * Nombre de demandes en cours (statut Proposé ou Approuvé).
   */
  enCours: number;

  /**
   * Nombre total de demandes de changement de l'organisation.
   */
  total: number;
}
