/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ComponentsVueEntity {

  /**
   * Nombre d'applications représentées.
   */
  applicationCount: number;

  /**
   * Nombre d'échanges applicatifs représentés.
   */
  echangeCount: number;

  /**
   * Contenu SVG du diagramme.
   */
  svg: string;
}
