/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ConformiteItemDto {

  /**
   * Commentaire associe au statut de conformite
   */
  commentaire?: string;

  /**
   * Identifiant de la politique de gouvernance
   */
  politiqueId: string;

  /**
   * Statut de conformite a la politique
   */
  statut: 'CONFORME' | 'NON_CONFORME' | 'A_EVALUER';
}
