/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateEchangeDto {

  /**
   * Description de l'échange applicatif.
   */
  description?: string;

  /**
   * Protocole utilisé pour l'échange (ex. REST, SOAP, EDI, SFTP).
   */
  protocole?: string;

  /**
   * Identifiant de l'application source de l'échange.
   */
  sourceId: string;

  /**
   * Identifiant de l'application cible de l'échange.
   */
  targetId: string;

  /**
   * Nature du couplage : SYNCHRONE (appel direct), ASYNCHRONE (bus/événement), BATCH (fichier/ETL).
   */
  typeFlux?: 'SYNCHRONE' | 'ASYNCHRONE' | 'BATCH';
}
