/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateApplicationServiceDto {

  /**
   * Description du service applicatif.
   */
  description?: string;

  /**
   * Nom du service applicatif.
   */
  nom: string;
}
