/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTechComponentDto {

  /**
   * Description du composant technologique
   */
  description?: string;

  /**
   * Nom du composant technologique
   */
  nom: string;

  /**
   * Position horizontale sur le canevas
   */
  positionX?: number;

  /**
   * Position verticale sur le canevas
   */
  positionY?: number;

  /**
   * Type du composant technologique
   */
  type: 'SERVEUR' | 'RESEAU' | 'CLOUD' | 'BASE_DE_DONNEES' | 'MIDDLEWARE';
}
