/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDataRelationDto {

  /**
   * Cardinalite de la relation
   */
  cardinalite: 'UN_A_UN' | 'UN_A_PLUSIEURS' | 'PLUSIEURS_A_PLUSIEURS';

  /**
   * Libelle de la relation
   */
  label?: string;

  /**
   * Identifiant de l'entite source
   */
  sourceId: string;

  /**
   * Identifiant de l'entite cible
   */
  targetId: string;
}
