/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateInvitationDto {

  /**
   * Coordonnées de contact du futur membre.
   */
  contact?: string;

  /**
   * Adresse e-mail de la personne invitée.
   */
  email: string;

  /**
   * Poste occupé par le futur membre.
   */
  poste?: string;

  /**
   * Rôle attribué à la personne une fois l'invitation acceptée.
   */
  role: 'ADMINISTRATEUR' | 'ARCHITECTE';

  /**
   * Identifiant du service auquel rattacher le futur membre.
   */
  serviceId?: string;
}
