/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateRelationDto {

  /**
   * Identifiant de l'élément source de la relation.
   */
  sourceId: string;

  /**
   * Identifiant de l'élément cible de la relation.
   */
  targetId: string;

  /**
   * Type de relation ArchiMate.
   */
  type: 'ASSIGNATION' | 'COMPOSITION' | 'REALISATION' | 'ASSOCIATION';
}
