/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateProjetDto {

  /**
   * Cout estime du projet
   */
  coutEstime?: string;

  /**
   * Date de debut du projet
   */
  dateDebut?: string;

  /**
   * Date de fin du projet
   */
  dateFin?: string;

  /**
   * Description du projet
   */
  description?: string;

  /**
   * Nom du projet
   */
  nom: string;

  /**
   * Priorite du projet
   */
  priorite?: 'HAUTE' | 'MOYENNE' | 'BASSE';
}
