/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePolitiqueDto {

  /**
   * Description de la politique de gouvernance
   */
  description?: string;

  /**
   * Nom de la politique de gouvernance
   */
  nom: string;
}
