/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateApplicationDto {

  /**
   * Description de l'application.
   */
  description?: string;

  /**
   * Nom de l'application.
   */
  nom: string;

  /**
   * Position horizontale de l'application sur le canevas.
   */
  positionX?: number;

  /**
   * Position verticale de l'application sur le canevas.
   */
  positionY?: number;
}
