/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateArchiApplicativeFluxDto {

  /**
   * Libellé affiché sur le flux.
   */
  label?: string;

  /**
   * Identifiant de l'élément source du flux.
   */
  sourceId: string;

  /**
   * Identifiant de l'élément cible du flux.
   */
  targetId: string;

  /**
   * Type du flux entre les deux éléments.
   */
  type?: 'API' | 'DONNEES' | 'AUTHENTIFICATION' | 'RESEAU';
}
