/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateBpmnFlowDto {

  /**
   * Libelle affiche sur le flux
   */
  label?: string;

  /**
   * Identifiant de l'element source du flux
   */
  sourceId: string;

  /**
   * Identifiant de l'element cible du flux
   */
  targetId: string;
}
