/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateElementDto {

  /**
   * Identifiant de la capacité métier associée.
   */
  capaciteMetierId?: string;

  /**
   * Catégorie de l'exigence, applicable lorsque l'élément est une exigence.
   */
  categorieExigence?: 'FONCTIONNELLE' | 'NON_FONCTIONNELLE';

  /**
   * Description de l'élément ArchiMate.
   */
  description?: string;

  /**
   * Nom de l'élément ArchiMate.
   */
  nom: string;

  /**
   * Position horizontale de l'élément sur le canevas.
   */
  positionX?: number;

  /**
   * Position verticale de l'élément sur le canevas.
   */
  positionY?: number;

  /**
   * Type de l'élément ArchiMate.
   */
  type: 'VISION' | 'OBJECTIF_ARCHIMATE' | 'PRINCIPE' | 'EXIGENCE' | 'ACTEUR_METIER' | 'ROLE_METIER' | 'PROCESSUS_METIER' | 'SERVICE_METIER' | 'OBJET_METIER';
}
