/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateMembreDto {

  /**
   * Coordonnées de contact du membre.
   */
  contact?: string;

  /**
   * Adresse email du membre.
   */
  email: string;

  /**
   * Nom complet du membre.
   */
  nom: string;

  /**
   * Mot de passe, minimum 8 caractères.
   */
  password: string;

  /**
   * Poste occupé par le membre.
   */
  poste?: string;

  /**
   * Rôle attribué au membre.
   */
  role: 'SUPERADMIN' | 'ADMINISTRATEUR' | 'ARCHITECTE';

  /**
   * Identifiant du service auquel rattacher le membre.
   */
  serviceId?: string;
}
