/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateArchiApplicativeElementDto {

  /**
   * Description détaillée de l'élément.
   */
  description?: string;

  /**
   * Nom de l'élément d'architecture applicative.
   */
  nom: string;

  /**
   * Position horizontale sur le canevas.
   */
  positionX?: number;

  /**
   * Position verticale sur le canevas.
   */
  positionY?: number;

  /**
   * Type de l'élément d'architecture applicative.
   */
  type: 'APPLICATION' | 'UTILISATEUR_INTERNE' | 'UTILISATEUR_EXTERNE' | 'SYSTEME_EXTERNE' | 'BASE_DE_DONNEES' | 'INFRASTRUCTURE' | 'SECURITE';
}
