/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateSolutionDto {

  /**
   * Description de la solution
   */
  description?: string;

  /**
   * Nom de la solution
   */
  nom: string;

  /**
   * Plan de mise en oeuvre de la solution
   */
  planMiseOeuvre?: string;

  /**
   * Statut de la solution
   */
  statut?: 'PROPOSEE' | 'RETENUE' | 'REJETEE';
}
