/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateBpmnProcessusDto {

  /**
   * Description du processus BPMN
   */
  description?: string;

  /**
   * Étapes du processus en langage naturel, une par ligne. Si renseigné à la création, une proposition de diagramme (éléments + flux) est générée automatiquement.
   */
  etapes?: string;

  /**
   * Nom du processus BPMN
   */
  nom: string;

  /**
   * Type du processus BPMN
   */
  type?: 'METIER' | 'SUPPORT' | 'PILOTAGE';
}
