/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateObjectifDto {

  /**
   * Description de l'objectif.
   */
  description?: string;

  /**
   * Nom de l'objectif.
   */
  nom: string;

  /**
   * Sous-objectif rattaché.
   */
  sousObjectif?: string;
}
