/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDataAttributeDto {

  /**
   * Nom de l'attribut
   */
  nom: string;

  /**
   * Type de donnee de l'attribut
   */
  type: string;
}
