/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateServiceDto {

  /**
   * Description du service.
   */
  description?: string;

  /**
   * Nom du service.
   */
  nom: string;

  /**
   * Identifiant du service parent.
   */
  parentId?: string;

  /**
   * Identifiant du membre qui occupe ce poste (titulaire).
   */
  titulaireId?: string;
}
