/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDataEntityDto {

  /**
   * Description de l'entite de donnees
   */
  description?: string;

  /**
   * Nom de l'entite de donnees
   */
  nom: string;

  /**
   * Position horizontale sur le canevas
   */
  positionX?: number;

  /**
   * Position verticale sur le canevas
   */
  positionY?: number;

  /**
   * Proprietaire de l'entite de donnees
   */
  proprietaire?: string;
}
