/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateZoneDto {

  /**
   * Nom de la zone d'urbanisation.
   */
  nom: string;

  /**
   * Identifiant de la zone parente.
   */
  parentId?: string;

  /**
   * Type de la zone d'urbanisation.
   */
  type: 'ZONE' | 'QUARTIER' | 'ILOT';
}
