/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DataEntityRefEntity } from '../models/data-entity-ref-entity';
export interface DataRelationDetailEntity {

  /**
   * Cardinalite de la relation.
   */
  cardinalite: 'UN_A_UN' | 'UN_A_PLUSIEURS' | 'PLUSIEURS_A_PLUSIEURS';

  /**
   * Identifiant de la relation.
   */
  id: string;

  /**
   * Libelle de la relation.
   */
  label?: string | null;

  /**
   * Entite de donnees source.
   */
  source: DataEntityRefEntity;

  /**
   * Identifiant de l'entite source.
   */
  sourceId: string;

  /**
   * Entite de donnees cible.
   */
  target: DataEntityRefEntity;

  /**
   * Identifiant de l'entite cible.
   */
  targetId: string;
}
