/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DataAttributeEntity {

  /**
   * Identifiant de l'entite de donnees a laquelle l'attribut appartient.
   */
  entityId: string;

  /**
   * Identifiant de l'attribut.
   */
  id: string;

  /**
   * Nom de l'attribut.
   */
  nom: string;

  /**
   * Type de donnee de l'attribut (texte libre, ex. 'string', 'int').
   */
  type: string;
}
