/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DataEntityItemDto {

  /**
   * Description de l'entité de données.
   */
  description?: string;

  /**
   * Nom de l'entité de données.
   */
  nom: string;
}
