/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DataEntityRefEntity {

  /**
   * Date de creation.
   */
  createdAt: string;

  /**
   * Description de l'entite de donnees.
   */
  description?: string | null;

  /**
   * Identifiant de l'entite de donnees.
   */
  id: string;

  /**
   * Nom de l'entite de donnees.
   */
  nom: string;

  /**
   * Identifiant de l'organisation proprietaire.
   */
  organisationId: string;

  /**
   * Position horizontale sur le canevas.
   */
  positionX?: number | null;

  /**
   * Position verticale sur le canevas.
   */
  positionY?: number | null;

  /**
   * Proprietaire de l'entite de donnees.
   */
  proprietaire?: string | null;

  /**
   * Statut de l'entite de donnees.
   */
  statut: 'AS_IS' | 'TO_BE' | 'LES_DEUX';

  /**
   * Date de derniere mise a jour.
   */
  updatedAt: string;
}
