/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DataAttributeEntity } from '../models/data-attribute-entity';
import { DataEntityCountEntity } from '../models/data-entity-count-entity';
export interface DataEntityEntity {

  /**
   * Compteur des relations imbriquees (present sur la liste, absent sur la recuperation par identifiant).
   */
  '_count'?: DataEntityCountEntity;

  /**
   * Attributs de l'entite de donnees.
   */
  attributs: Array<DataAttributeEntity>;

  /**
   * Date de creation.
   */
  createdAt: string;

  /**
   * Description de l'entite de donnees.
   */
  description?: string | null;

  /**
   * Identifiant de l'entite de donnees.
   */
  id: string;

  /**
   * Nom de l'entite de donnees.
   */
  nom: string;

  /**
   * Identifiant de l'organisation proprietaire.
   */
  organisationId: string;

  /**
   * Position horizontale sur le canevas.
   */
  positionX?: number | null;

  /**
   * Position verticale sur le canevas.
   */
  positionY?: number | null;

  /**
   * Proprietaire de l'entite de donnees.
   */
  proprietaire?: string | null;

  /**
   * Statut de l'entite de donnees.
   */
  statut: 'AS_IS' | 'TO_BE' | 'LES_DEUX';

  /**
   * Date de derniere mise a jour.
   */
  updatedAt: string;
}
