/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DemandeChangementEntity {

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Description de la demande de changement.
   */
  description?: string | null;

  /**
   * Identifiant de la demande de changement.
   */
  id: string;

  /**
   * Identifiant de l'organisation propriétaire de la demande.
   */
  organisationId: string;

  /**
   * Statut de la demande de changement.
   */
  statut: 'PROPOSE' | 'APPROUVE' | 'REJETE' | 'IMPLEMENTE';

  /**
   * Titre de la demande de changement.
   */
  titre: string;

  /**
   * Date de dernière mise à jour.
   */
  updatedAt: string;
}
