/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeployerApplicationDto {

  /**
   * Identifiant de l'application a deployer
   */
  applicationId: string;

  /**
   * Identifiant du composant technologique cible
   */
  techComponentId: string;
}
