/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationEntity } from '../models/application-entity';
export interface EchangeEntity {

  /**
   * Date de création de l'échange.
   */
  createdAt: string;

  /**
   * Description de l'échange.
   */
  description?: string | null;

  /**
   * Identifiant de l'échange.
   */
  id: string;

  /**
   * Protocole utilisé pour l'échange (ex. REST, SOAP, EDI, SFTP).
   */
  protocole?: string | null;

  /**
   * Nature du couplage : SYNCHRONE (appel direct REST/SOAP), ASYNCHRONE (bus/événement), BATCH (fichier/ETL).
   */
  typeFlux: 'SYNCHRONE' | 'ASYNCHRONE' | 'BATCH';

  /**
   * Application source de l'échange.
   */
  source: ApplicationEntity;

  /**
   * Identifiant de l'application source.
   */
  sourceId: string;

  /**
   * Application cible de l'échange.
   */
  target: ApplicationEntity;

  /**
   * Identifiant de l'application cible.
   */
  targetId: string;
}
