/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationEntity } from '../models/application-entity';
export interface EchangeEntity {

  /**
   * Date de création de l'échange.
   */
  createdAt: string;

  /**
   * Description de l'échange.
   */
  description?: string | null;

  /**
   * Identifiant de l'échange.
   */
  id: string;

  /**
   * Protocole utilisé pour l'échange.
   */
  protocole?: string | null;

  /**
   * Application source de l'échange.
   */
  source: ApplicationEntity;

  /**
   * Identifiant de l'application source.
   */
  sourceId: string;

  /**
   * Application cible de l'échange.
   */
  target: ApplicationEntity;

  /**
   * Identifiant de l'application cible.
   */
  targetId: string;
}
