/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CapaciteRefEntity } from '../models/capacite-ref-entity';
import { RelationCountEntity } from '../models/relation-count-entity';
import { RelationSourceEntity } from '../models/relation-source-entity';
import { RelationTargetEntity } from '../models/relation-target-entity';
export interface ElementArchimateEntity {

  /**
   * Compteur des relations de l'élément.
   */
  '_count'?: RelationCountEntity;

  /**
   * Capacité métier associée à cet élément.
   */
  capacite?: (CapaciteRefEntity & {
}) | null;

  /**
   * Identifiant de la capacité métier associée.
   */
  capaciteMetierId?: string | null;

  /**
   * Sous-catégorie de l'exigence, pertinente uniquement quand type = EXIGENCE.
   */
  categorieExigence?: ('FONCTIONNELLE' | 'NON_FONCTIONNELLE') | null;

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Description de l'élément ArchiMate.
   */
  description?: string | null;

  /**
   * Hauteur manuelle sur le canevas.
   */
  height?: number | null;

  /**
   * Identifiant de l'élément ArchiMate.
   */
  id: string;

  /**
   * Nom de l'élément ArchiMate.
   */
  nom: string;

  /**
   * Identifiant de l'organisation propriétaire.
   */
  organisationId: string;

  /**
   * Position horizontale manuelle sur le canevas.
   */
  positionX?: number | null;

  /**
   * Position verticale manuelle sur le canevas.
   */
  positionY?: number | null;

  /**
   * Relations où cet élément est la source.
   */
  relationsSource?: Array<RelationSourceEntity>;

  /**
   * Relations où cet élément est la cible.
   */
  relationsTarget?: Array<RelationTargetEntity>;

  /**
   * Statut de l'élément (AS_IS, TO_BE ou LES_DEUX).
   */
  statut: 'AS_IS' | 'TO_BE' | 'LES_DEUX';

  /**
   * Type de l'élément ArchiMate.
   */
  type: 'VISION' | 'OBJECTIF_ARCHIMATE' | 'PRINCIPE' | 'EXIGENCE' | 'ACTEUR_METIER' | 'ROLE_METIER' | 'PROCESSUS_METIER' | 'SERVICE_METIER' | 'OBJET_METIER';

  /**
   * Date de dernière modification.
   */
  updatedAt: string;

  /**
   * Largeur manuelle sur le canevas.
   */
  width?: number | null;
}
