/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ElementRefEntity {

  /**
   * Identifiant de l'élément ArchiMate.
   */
  id: string;

  /**
   * Nom de l'élément ArchiMate.
   */
  nom: string;

  /**
   * Type de l'élément ArchiMate.
   */
  type: 'VISION' | 'OBJECTIF_ARCHIMATE' | 'PRINCIPE' | 'EXIGENCE' | 'ACTEUR_METIER' | 'ROLE_METIER' | 'PROCESSUS_METIER' | 'SERVICE_METIER' | 'OBJET_METIER';
}
