/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ElementCountEntity {

  /**
   * Nombre d'éléments ArchiMate rattachés à cette capacité.
   */
  elements: number;
}
