/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EnqueteReponseItemDto {

  /**
   * Commentaire libre du repondant
   */
  commentaire?: string;

  /**
   * Nom ou identifiant du repondant
   */
  repondant: string;

  /**
   * Score attribue par le repondant, de 1 a 5
   */
  score: number;
}
