/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EnqueteReponseEntity {

  /**
   * Commentaire libre du répondant.
   */
  commentaire?: string | null;

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Identifiant de la réponse.
   */
  id: string;

  /**
   * Identifiant de l'organisation propriétaire.
   */
  organisationId: string;

  /**
   * Nom ou identifiant du répondant.
   */
  repondant: string;

  /**
   * Score attribué par le répondant, de 1 à 5.
   */
  score: number;
}
