/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ForgotPasswordDto {

  /**
   * Adresse e-mail du compte dont le mot de passe est oublié.
   */
  email: string;
}
