/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GapLinkItemDto {

  /**
   * Domaine architectural de l'écart (Analyse des écarts).
   */
  domaine: 'OBJECTIF' | 'METIER' | 'DONNEES' | 'APPLICATIF' | 'TECHNOLOGIQUE';

  /**
   * Identifiant de l'élément d'origine (objectif, élément ArchiMate, entité de données, application ou composant technologique selon le domaine).
   */
  elementId: string;

  /**
   * Nom de l'élément d'origine, recopié au moment du lien (pour affichage sans recharger sa source).
   */
  elementNom: string;
}
