/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EnqueteReponseItemDto } from '../models/enquete-reponse-item-dto';
export interface ImportEnqueteDto {

  /**
   * Liste des reponses a importer
   */
  items: Array<EnqueteReponseItemDto>;
}
