/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvitationEntity {

  /**
   * Contact prévu.
   */
  contact?: string | null;

  /**
   * Date de création de l'invitation.
   */
  createdAt: string;

  /**
   * Adresse e-mail invitée.
   */
  email: string;

  /**
   * Date d'expiration du lien.
   */
  expiresAt: string;

  /**
   * Identifiant de l'invitation.
   */
  id: string;

  /**
   * Nom de l'administrateur qui a envoyé l'invitation.
   */
  invitedByNom?: string | null;

  /**
   * Poste prévu.
   */
  poste?: string | null;

  /**
   * Rôle attribué à l'acceptation.
   */
  role: 'SUPERADMIN' | 'ADMINISTRATEUR' | 'ARCHITECTE';

  /**
   * Service de rattachement prévu.
   */
  serviceId?: string | null;

  /**
   * Statut de l'invitation.
   */
  statut: 'EN_ATTENTE' | 'ACCEPTEE' | 'REVOKEE';
}
