/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvitationPublicEntity {

  /**
   * Adresse e-mail invitée (pré-remplie, non modifiable).
   */
  email: string;

  /**
   * Nom de l'organisation qui invite.
   */
  organisationNom: string;

  /**
   * Rôle qui sera attribué à l'acceptation.
   */
  role: 'SUPERADMIN' | 'ADMINISTRATEUR' | 'ARCHITECTE';
}
