/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LayoutPositionEntity {

  /**
   * Identifiant de l'élément repositionné.
   */
  id: string;

  /**
   * Abscisse (px).
   */
  positionX: number;

  /**
   * Ordonnée (px).
   */
  positionY: number;
}
