/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GapLinkItemDto } from '../models/gap-link-item-dto';
export interface LinkGapsDto {

  /**
   * Liste complète des écarts adressés par cette solution (remplace la liste existante).
   */
  items: Array<GapLinkItemDto>;
}
