/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoginDto {

  /**
   * Adresse e-mail de l'utilisateur.
   */
  email: string;

  /**
   * Mot de passe, 8 caractères minimum.
   */
  password: string;
}
