/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MeEntity {

  /**
   * URL de l'avatar de l'utilisateur.
   */
  avatarUrl?: string | null;

  /**
   * Date de création du compte.
   */
  createdAt: string;

  /**
   * Adresse e-mail de l'utilisateur.
   */
  email: string;

  /**
   * Identifiant de l'utilisateur.
   */
  id: string;

  /**
   * Nom de l'utilisateur.
   */
  nom: string;

  /**
   * Rôle de l'utilisateur.
   */
  role: 'SUPERADMIN' | 'ADMINISTRATEUR' | 'ARCHITECTE';
}
