/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MembreEntity {

  /**
   * Coordonnées de contact du membre.
   */
  contact?: string | null;

  /**
   * Date de création du compte.
   */
  createdAt: string;

  /**
   * Adresse email du membre.
   */
  email: string;

  /**
   * Identifiant du membre.
   */
  id: string;

  /**
   * Nom du membre.
   */
  nom: string;

  /**
   * Poste occupé par le membre.
   */
  poste?: string | null;

  /**
   * Rôle attribué au membre.
   */
  role: 'SUPERADMIN' | 'ADMINISTRATEUR' | 'ARCHITECTE';

  /**
   * Identifiant du service auquel le membre est rattaché.
   */
  serviceId?: string | null;
}
