/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageResponseEntity {

  /**
   * Message de confirmation à afficher à l'utilisateur.
   */
  message: string;
}
