/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ObjectifItemDto {

  /**
   * Description de l'objectif.
   */
  description?: string;

  /**
   * Nom de l'objectif.
   */
  nom: string;
}
