/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ObjectifRefEntity {

  /**
   * Identifiant de l'objectif.
   */
  id: string;

  /**
   * Nom de l'objectif.
   */
  nom: string;

  /**
   * Statut de l'objectif.
   */
  statut: 'AS_IS' | 'TO_BE' | 'LES_DEUX';
}
