/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ObjectifRefEntity } from '../models/objectif-ref-entity';
export interface ObjectifEntity {

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Description de l'objectif.
   */
  description?: string | null;

  /**
   * Identifiant de l'objectif.
   */
  id: string;

  /**
   * Nom de l'objectif.
   */
  nom: string;

  /**
   * Objectif AS-IS dont cet objectif TO-BE est l'évolution.
   */
  objectifAsIs?: (ObjectifRefEntity & {
}) | null;

  /**
   * Identifiant de l'objectif AS-IS dont cet objectif TO-BE est l'évolution.
   */
  objectifAsIsId?: string | null;

  /**
   * Objectifs TO-BE qui sont l'évolution de cet objectif AS-IS.
   */
  objectifsToBe?: Array<ObjectifRefEntity>;

  /**
   * Identifiant de l'organisation propriétaire.
   */
  organisationId: string;

  /**
   * Sous-objectif rattaché.
   */
  sousObjectif?: string | null;

  /**
   * Statut de l'objectif pour l'analyse des écarts (AS_IS, TO_BE ou LES_DEUX).
   */
  statut: 'AS_IS' | 'TO_BE' | 'LES_DEUX';

  /**
   * Date de dernière modification.
   */
  updatedAt: string;
}
