/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ObjectifEntity {

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Description de l'objectif.
   */
  description?: string | null;

  /**
   * Identifiant de l'objectif.
   */
  id: string;

  /**
   * Nom de l'objectif.
   */
  nom: string;

  /**
   * Identifiant de l'organisation propriétaire.
   */
  organisationId: string;

  /**
   * Sous-objectif rattaché.
   */
  sousObjectif?: string | null;

  /**
   * Date de dernière modification.
   */
  updatedAt: string;
}
