/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrganisationUsersCountEntity {

  /**
   * Nombre d'utilisateurs de cette organisation.
   */
  users: number;
}
