/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationEntity } from '../models/application-entity';
import { CapaciteMetierEntity } from '../models/capacite-metier-entity';
import { ElementArchimateEntity } from '../models/element-archimate-entity';
import { OrganisationEntity } from '../models/organisation-entity';
import { RelationArchimateEntity } from '../models/relation-archimate-entity';
import { ZoneUrbanisationEntity } from '../models/zone-urbanisation-entity';
export interface OrganisationExportEntity {

  /**
   * Applications du portefeuille applicatif de l'organisation.
   */
  applications: Array<ApplicationEntity>;

  /**
   * Capacités métier de l'organisation.
   */
  capacites: Array<CapaciteMetierEntity>;

  /**
   * Éléments ArchiMate de l'organisation.
   */
  elements: Array<ElementArchimateEntity>;

  /**
   * Date et heure de génération de l'export (ISO 8601).
   */
  exportedAt: string;

  /**
   * Organisation exportée.
   */
  organisation: OrganisationEntity;

  /**
   * Relations ArchiMate de l'organisation.
   */
  relations: Array<RelationArchimateEntity>;

  /**
   * Zones d'urbanisation de l'organisation.
   */
  zones: Array<ZoneUrbanisationEntity>;
}
