/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrganisationEntity {

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Description de l'organisation.
   */
  description?: string | null;

  /**
   * Identifiant de l'organisation.
   */
  id: string;

  /**
   * URL du logo de l'organisation.
   */
  logoUrl?: string | null;

  /**
   * Nom de l'organisation.
   */
  nom: string;

  /**
   * Pays de l'organisation.
   */
  pays?: string | null;

  /**
   * Problèmes que l'organisation cherche à résoudre.
   */
  problemesResoudre?: string | null;

  /**
   * Secteur d'activité de l'organisation.
   */
  secteur?: string | null;

  /**
   * Statut de validation de l'organisation.
   */
  statut: 'EN_ATTENTE' | 'VALIDEE' | 'REJETEE';

  /**
   * Taille de l'organisation.
   */
  taille?: string | null;

  /**
   * Date de dernière modification.
   */
  updatedAt: string;

  /**
   * Vision stratégique de l'organisation.
   */
  vision?: string | null;
}
