/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PartiePrenanteItemDto {

  /**
   * Nom de la partie prenante.
   */
  nom: string;

  /**
   * Rôle de la partie prenante.
   */
  role?: string;
}
