/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PartiePrenanteEntity {

  /**
   * Date de création de la partie prenante.
   */
  createdAt: string;

  /**
   * Identifiant de la partie prenante.
   */
  id: string;

  /**
   * Nom de la partie prenante.
   */
  nom: string;

  /**
   * Identifiant de l'organisation propriétaire de la partie prenante.
   */
  organisationId: string;

  /**
   * Rôle de la partie prenante.
   */
  role?: string | null;

  /**
   * Date de dernière modification de la partie prenante.
   */
  updatedAt: string;
}
