/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PolitiqueRefEntity {

  /**
   * Identifiant de la politique de gouvernance.
   */
  id: string;

  /**
   * Nom de la politique de gouvernance.
   */
  nom: string;
}
