/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PolitiqueEntity {

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Description de la politique de gouvernance.
   */
  description?: string | null;

  /**
   * Identifiant de la politique de gouvernance.
   */
  id: string;

  /**
   * Nom de la politique de gouvernance.
   */
  nom: string;

  /**
   * Identifiant de l'organisation propriétaire de la politique.
   */
  organisationId: string;

  /**
   * Date de dernière mise à jour.
   */
  updatedAt: string;
}
