/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PositionItemDto {

  /**
   * Identifiant de l'élément dont la position est mise à jour.
   */
  id: string;

  /**
   * Position horizontale de l'élément sur le canevas.
   */
  positionX: number;

  /**
   * Position verticale de l'élément sur le canevas.
   */
  positionY: number;
}
