/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjetEntity {

  /**
   * Cout estime du projet.
   */
  coutEstime?: string | null;

  /**
   * Date de creation.
   */
  createdAt: string;

  /**
   * Date de debut du projet.
   */
  dateDebut?: string | null;

  /**
   * Date de fin du projet.
   */
  dateFin?: string | null;

  /**
   * Description du projet.
   */
  description?: string | null;

  /**
   * Identifiant du projet.
   */
  id: string;

  /**
   * Nom du projet.
   */
  nom: string;

  /**
   * Identifiant de l'organisation proprietaire.
   */
  organisationId: string;

  /**
   * Priorite du projet.
   */
  priorite: 'HAUTE' | 'MOYENNE' | 'BASSE';

  /**
   * Statut du projet.
   */
  statut: 'PLANIFIE' | 'EN_COURS' | 'TERMINE';

  /**
   * Date de derniere mise a jour.
   */
  updatedAt: string;
}
