/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActeurItemDto } from '../models/acteur-item-dto';
import { ApplicationItemDto } from '../models/application-item-dto';
import { BpmnProcessusItemDto } from '../models/bpmn-processus-item-dto';
import { CapaciteItemDto } from '../models/capacite-item-dto';
import { DataEntityItemDto } from '../models/data-entity-item-dto';
import { ObjectifItemDto } from '../models/objectif-item-dto';
import { PartiePrenanteItemDto } from '../models/partie-prenante-item-dto';
import { TechComponentItemDto } from '../models/tech-component-item-dto';
export interface RegisterDto {

  /**
   * Acteurs à pré-remplir pour l'organisation.
   */
  acteurs?: Array<ActeurItemDto>;

  /**
   * Applications à pré-remplir pour l'organisation.
   */
  applications?: Array<ApplicationItemDto>;

  /**
   * Processus BPMN à pré-remplir pour l'organisation.
   */
  bpmnProcessus?: Array<BpmnProcessusItemDto>;

  /**
   * Capacités métier à pré-remplir pour l'organisation.
   */
  capacitesMetier?: Array<CapaciteItemDto>;

  /**
   * Entités de données à pré-remplir pour l'organisation.
   */
  dataEntities?: Array<DataEntityItemDto>;

  /**
   * Adresse e-mail du premier utilisateur, administrateur de l'organisation.
   */
  email: string;

  /**
   * URL du logo de l'organisation.
   */
  logoUrl?: string;

  /**
   * Nom du premier utilisateur.
   */
  nom: string;

  /**
   * Objectifs à pré-remplir pour l'organisation.
   */
  objectifs?: Array<ObjectifItemDto>;

  /**
   * Description de l'organisation.
   */
  organisationDescription?: string;

  /**
   * Nom de l'organisation.
   */
  organisationNom: string;

  /**
   * Parties prenantes à pré-remplir pour l'organisation.
   */
  partiesPrenantes?: Array<PartiePrenanteItemDto>;

  /**
   * Mot de passe, 8 caractères minimum.
   */
  password: string;

  /**
   * Pays de l'organisation.
   */
  pays?: string;

  /**
   * Problèmes que l'organisation cherche à résoudre.
   */
  problemesResoudre?: string;

  /**
   * Secteur d'activité de l'organisation.
   */
  secteur?: string;

  /**
   * Taille de l'organisation.
   */
  taille?: string;

  /**
   * Composants technologiques à pré-remplir pour l'organisation.
   */
  techComponents?: Array<TechComponentItemDto>;

  /**
   * Vision de l'organisation.
   */
  vision?: string;
}
