/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthOrganisationEntity } from '../models/auth-organisation-entity';
export interface RegisterResponseEntity {

  /**
   * Message de confirmation à afficher à l'utilisateur.
   */
  message: string;

  /**
   * Organisation nouvellement créée, au statut EN_ATTENTE.
   */
  organisation: AuthOrganisationEntity;
}
