/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthOrganisationEntity } from '../models/auth-organisation-entity';
import { AuthUserEntity } from '../models/auth-user-entity';
export interface RegisterResponseEntity {

  /**
   * Jeton JWT d'accès, également posé en cookie.
   */
  accessToken: string;

  /**
   * Organisation nouvellement créée pour l'utilisateur inscrit.
   */
  organisation: AuthOrganisationEntity;

  /**
   * Profil utilisateur authentifié.
   */
  user: AuthUserEntity;
}
