/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RelationCountEntity {

  /**
   * Nombre de relations où l'élément est la source.
   */
  relationsSource: number;

  /**
   * Nombre de relations où l'élément est la cible.
   */
  relationsTarget: number;
}
