/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ElementRefEntity } from '../models/element-ref-entity';
export interface RelationSourceEntity {

  /**
   * Date de création de la relation.
   */
  createdAt: string;

  /**
   * Identifiant de la relation.
   */
  id: string;

  /**
   * Identifiant de l'élément source.
   */
  sourceId: string;

  /**
   * Élément cible de la relation.
   */
  target: ElementRefEntity;

  /**
   * Identifiant de l'élément cible.
   */
  targetId: string;

  /**
   * Type de la relation ArchiMate.
   */
  type: 'ASSIGNATION' | 'COMPOSITION' | 'REALISATION' | 'ASSOCIATION';
}
