/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResetPasswordDto {

  /**
   * Nouveau mot de passe, 8 caractères minimum.
   */
  password: string;

  /**
   * Jeton reçu dans le lien de réinitialisation.
   */
  token: string;
}
