/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScoreItemDto {

  /**
   * Commentaire associe au score
   */
  commentaire?: string;

  /**
   * Identifiant du critere d'evaluation
   */
  critereId: string;

  /**
   * Score attribue au critere
   */
  score: number;
}
