/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ServiceMembreCountEntity } from '../models/service-membre-count-entity';
import { ServiceMembreEntity } from '../models/service-membre-entity';
import { ServiceParentRefEntity } from '../models/service-parent-ref-entity';
import { ServiceTitulaireRefEntity } from '../models/service-titulaire-ref-entity';
export interface ServiceEntity {

  /**
   * Compteur de membres rattachés à ce service (uniquement sur la liste).
   */
  '_count'?: ServiceMembreCountEntity;

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Description du service.
   */
  description?: string | null;

  /**
   * Services enfants directs, triés par nom (sur deux niveaux pour la liste, un niveau pour le détail).
   */
  enfants?: Array<ServiceEntity>;

  /**
   * Identifiant du service.
   */
  id: string;

  /**
   * Membres rattachés à ce service (uniquement sur la récupération par identifiant).
   */
  membres?: Array<ServiceMembreEntity>;

  /**
   * Nom du service.
   */
  nom: string;

  /**
   * Identifiant de l'organisation propriétaire.
   */
  organisationId: string;

  /**
   * Service parent (uniquement sur la récupération par identifiant).
   */
  parent?: (ServiceParentRefEntity & {
}) | null;

  /**
   * Identifiant du service parent, le cas échéant.
   */
  parentId?: string | null;

  /**
   * Membre qui occupe ce poste (null si vacant).
   */
  titulaire?: (ServiceTitulaireRefEntity & {
}) | null;

  /**
   * Identifiant du membre titulaire du poste, le cas échéant.
   */
  titulaireId?: string | null;

  /**
   * Date de dernière modification.
   */
  updatedAt: string;
}
