/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ServiceParentRefEntity {

  /**
   * Identifiant du service parent.
   */
  id: string;

  /**
   * Nom du service parent.
   */
  nom: string;
}
