/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ServiceMembreEntity {

  /**
   * Identifiant de l'utilisateur.
   */
  id: string;

  /**
   * Nom de l'utilisateur.
   */
  nom: string;

  /**
   * Rôle de l'utilisateur.
   */
  role: 'SUPERADMIN' | 'ADMINISTRATEUR' | 'ARCHITECTE';
}
