/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ServiceViewEntity {

  /**
   * Nombre de membres représentés dans la vue.
   */
  membreCount: number;

  /**
   * Nombre de services représentés dans la vue.
   */
  serviceCount: number;

  /**
   * Contenu SVG de l'organigramme généré.
   */
  svg: string;
}
