/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ServiceTitulaireRefEntity {

  /**
   * Identifiant du membre titulaire.
   */
  id: string;

  /**
   * Nom du membre titulaire.
   */
  nom: string;
}
