/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SimulatedEmailEntity {

  /**
   * Corps de l'e-mail.
   */
  body: string;

  /**
   * Objet de l'e-mail.
   */
  subject: string;

  /**
   * Adresse e-mail du destinataire.
   */
  to: string;
}
