/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SolutionGapEntity {

  /**
   * Date de création du lien.
   */
  createdAt: string;

  /**
   * Domaine architectural de l'écart.
   */
  domaine: 'OBJECTIF' | 'METIER' | 'DONNEES' | 'APPLICATIF' | 'TECHNOLOGIQUE';

  /**
   * Identifiant de l'élément d'origine.
   */
  elementId: string;

  /**
   * Nom de l'élément d'origine, recopié au moment du lien.
   */
  elementNom: string;

  /**
   * Identifiant du lien.
   */
  id: string;

  /**
   * Identifiant de la solution.
   */
  solutionId: string;
}
