/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SolutionGapRefEntity {

  /**
   * Identifiant de la solution.
   */
  id: string;

  /**
   * Nom de la solution.
   */
  nom: string;
}
