/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EvaluationScoreEntity } from '../models/evaluation-score-entity';
export interface SolutionEntity {

  /**
   * Avancement de la mise en oeuvre de la solution.
   */
  avancement: 'NON_DEMARRE' | 'EN_COURS' | 'TERMINE' | 'BLOQUE';

  /**
   * Commentaire de suivi de la solution.
   */
  commentaireSuivi?: string | null;

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Description de la solution.
   */
  description?: string | null;

  /**
   * Identifiant de la solution.
   */
  id: string;

  /**
   * Nom de la solution.
   */
  nom: string;

  /**
   * Identifiant de l'organisation propriétaire de la solution.
   */
  organisationId: string;

  /**
   * Plan de mise en oeuvre de la solution.
   */
  planMiseOeuvre?: string | null;

  /**
   * Scores d'évaluation de la solution (le critère détaillé n'est inclus que pour le détail d'une solution).
   */
  scores: Array<EvaluationScoreEntity>;

  /**
   * Statut de la solution.
   */
  statut: 'PROPOSEE' | 'RETENUE' | 'REJETEE';

  /**
   * Date de dernière mise à jour.
   */
  updatedAt: string;
}
