/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SolutionGapRefEntity {

  /**
   * Identifiant de la solution.
   */
  id: string;

  /**
   * Nom de la solution.
   */
  nom: string;

  /**
   * Avancement de la mise en oeuvre de la solution.
   */
  avancement: 'NON_DEMARRE' | 'EN_COURS' | 'TERMINE' | 'BLOQUE';
}
