/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrganisationUsersCountEntity } from '../models/organisation-users-count-entity';
export interface SuperAdminOrganisationWithCountEntity {

  /**
   * Compteur d'utilisateurs de cette organisation.
   */
  '_count': OrganisationUsersCountEntity;

  /**
   * Date de création.
   */
  createdAt: string;

  /**
   * Description de l'organisation.
   */
  description?: string | null;

  /**
   * Identifiant de l'organisation.
   */
  id: string;

  /**
   * URL du logo.
   */
  logoUrl?: string | null;

  /**
   * Nom de l'organisation.
   */
  nom: string;

  /**
   * Pays.
   */
  pays?: string | null;

  /**
   * Problèmes à résoudre par cette organisation.
   */
  problemesResoudre?: string | null;

  /**
   * Secteur d'activité.
   */
  secteur?: string | null;

  /**
   * Statut de validation de l'organisation.
   */
  statut: 'EN_ATTENTE' | 'VALIDEE' | 'REJETEE';

  /**
   * Taille de l'organisation.
   */
  taille?: string | null;

  /**
   * Date de dernière modification.
   */
  updatedAt: string;

  /**
   * Date de validation par le superadmin.
   */
  validatedAt?: string | null;

  /**
   * Vision d'architecture (étape 1 de l'assistant TOGAF ADM).
   */
  vision?: string | null;
}
