/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TechComponentItemDto {

  /**
   * Description du composant technologique.
   */
  description?: string;

  /**
   * Nom du composant technologique.
   */
  nom: string;

  /**
   * Type du composant technologique.
   */
  type: 'SERVEUR' | 'RESEAU' | 'CLOUD' | 'BASE_DE_DONNEES' | 'MIDDLEWARE' | 'ORDINATEUR_PORTABLE' | 'ROUTEUR_RESEAU' | 'CAPTEUR_IOT_CONSOMMATION' | 'SMARTPHONE_PROFESSIONNEL' | 'STOCKAGE_NAS' | 'BASE_DE_DONNEES_POSTGRESQL' | 'SERVEUR_APPLICATIONS' | 'API_REST' | 'LOGICIEL_CYBERSECURITE' | 'SYSTEME_EXPLOITATION_LINUX' | 'PLATEFORME_CLOUD' | 'PARE_FEU' | 'SWITCH' | 'VPN' | 'CONNEXION_INTERNET_FIBRE' | 'AUTRE';
}
