/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TechComponentItemDto {

  /**
   * Description du composant technologique.
   */
  description?: string;

  /**
   * Nom du composant technologique.
   */
  nom: string;

  /**
   * Type du composant technologique.
   */
  type: 'SERVEUR' | 'RESEAU' | 'CLOUD' | 'BASE_DE_DONNEES' | 'MIDDLEWARE';
}
