/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TechDeploiementDetailEntity } from '../models/tech-deploiement-detail-entity';
export interface TechComponentEntity {

  /**
   * Date de creation.
   */
  createdAt: string;

  /**
   * Deploiements (applications deployees sur ce composant).
   */
  deploiements: Array<TechDeploiementDetailEntity>;

  /**
   * Description du composant technologique.
   */
  description?: string | null;

  /**
   * Identifiant du composant technologique.
   */
  id: string;

  /**
   * Nom du composant technologique.
   */
  nom: string;

  /**
   * Identifiant de l'organisation proprietaire.
   */
  organisationId: string;

  /**
   * Position horizontale sur le canevas.
   */
  positionX?: number | null;

  /**
   * Position verticale sur le canevas.
   */
  positionY?: number | null;

  /**
   * Statut du composant technologique.
   */
  statut: 'AS_IS' | 'TO_BE' | 'LES_DEUX';

  /**
   * Type du composant technologique.
   */
  type: 'SERVEUR' | 'RESEAU' | 'CLOUD' | 'BASE_DE_DONNEES' | 'MIDDLEWARE';

  /**
   * Date de derniere mise a jour.
   */
  updatedAt: string;
}
