/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TechDeploiementEntity {

  /**
   * Identifiant de l'application deployee.
   */
  applicationId: string;

  /**
   * Identifiant du composant technologique cible.
   */
  techComponentId: string;
}
