/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationRefEntity } from '../models/application-ref-entity';
export interface TechDeploiementDetailEntity {

  /**
   * Application deployee.
   */
  application: ApplicationRefEntity;

  /**
   * Identifiant de l'application deployee.
   */
  applicationId: string;

  /**
   * Identifiant du composant technologique cible.
   */
  techComponentId: string;
}
