/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateVisionCanvasDto {

  /**
   * Objectifs metier vises par le produit
   */
  businessGoals?: string;

  /**
   * Canaux de distribution ou de communication
   */
  channels?: string;

  /**
   * Concurrents identifies
   */
  competitors?: string;

  /**
   * Facteurs de cout associes
   */
  costFactors?: string;

  /**
   * Besoins adresses par le produit
   */
  needs?: string;

  /**
   * Description du produit
   */
  product?: string;

  /**
   * Sources de revenus envisagees
   */
  revenueStreams?: string;

  /**
   * Groupe cible du produit
   */
  targetGroup?: string;
}
