/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePositionDto {

  /**
   * Position horizontale de l'élément sur le canevas.
   */
  positionX: number;

  /**
   * Position verticale de l'élément sur le canevas.
   */
  positionY: number;
}
