/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PositionItemDto } from '../models/position-item-dto';
export interface UpdatePositionsBatchDto {

  /**
   * Liste des positions à mettre à jour par lot.
   */
  items: Array<PositionItemDto>;
}
