/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConformiteItemDto } from '../models/conformite-item-dto';
export interface UpdateConformitesDto {

  /**
   * Liste des conformites a mettre a jour
   */
  items: Array<ConformiteItemDto>;
}
