/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateZoneDto {

  /**
   * Nouveau nom de la zone d'urbanisation.
   */
  nom?: string;

  /**
   * Identifiant de la zone parente, ou null pour retirer le rattachement.
   */
  parentId?: string | null;
}
