/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateMembreDto {

  /**
   * Coordonnées de contact du membre.
   */
  contact?: string;

  /**
   * Poste occupé par le membre.
   */
  poste?: string;

  /**
   * Rôle attribué au membre.
   */
  role?: 'SUPERADMIN' | 'ADMINISTRATEUR' | 'ARCHITECTE';

  /**
   * Identifiant du service auquel rattacher le membre, ou null pour le détacher.
   */
  serviceId?: string | null;
}
