/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateServiceDto {

  /**
   * Description du service.
   */
  description?: string;

  /**
   * Nom du service.
   */
  nom?: string;

  /**
   * Identifiant du service parent, ou null pour le retirer.
   */
  parentId?: string | null;
}
