/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateApplicationDto {

  /**
   * Nouvelle description de l'application.
   */
  description?: string;

  /**
   * Nouveau nom de l'application.
   */
  nom?: string;

  /**
   * Nouvelle position horizontale de l'application sur le canevas.
   */
  positionX?: number;

  /**
   * Nouvelle position verticale de l'application sur le canevas.
   */
  positionY?: number;
}
