/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateDataEntityDto {

  /**
   * Description de l'entite de donnees
   */
  description?: string;

  /**
   * Nom de l'entite de donnees
   */
  nom?: string;

  /**
   * Position horizontale sur le canevas
   */
  positionX?: number;

  /**
   * Position verticale sur le canevas
   */
  positionY?: number;

  /**
   * Proprietaire de l'entite de donnees
   */
  proprietaire?: string;

  /**
   * Statut de l'entite de donnees
   */
  statut?: 'AS_IS' | 'TO_BE' | 'LES_DEUX';
}
