/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScoreItemDto } from '../models/score-item-dto';
export interface UpdateScoresDto {

  /**
   * Liste des scores a mettre a jour
   */
  items: Array<ScoreItemDto>;
}
