/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateSolutionDto {

  /**
   * Avancement de la mise en oeuvre de la solution
   */
  avancement?: 'NON_DEMARRE' | 'EN_COURS' | 'TERMINE' | 'BLOQUE';

  /**
   * Commentaire de suivi de la solution
   */
  commentaireSuivi?: string;

  /**
   * Description de la solution
   */
  description?: string;

  /**
   * Nom de la solution
   */
  nom?: string;

  /**
   * Plan de mise en oeuvre de la solution
   */
  planMiseOeuvre?: string;

  /**
   * Statut de la solution
   */
  statut?: 'PROPOSEE' | 'RETENUE' | 'REJETEE';
}
