/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateMeDto {

  /**
   * URL de l'avatar de l'utilisateur.
   */
  avatarUrl?: string;

  /**
   * Nom affiché de l'utilisateur.
   */
  nom?: string;
}
