/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateOrganisationDto {

  /**
   * Description de l'organisation.
   */
  description?: string;

  /**
   * URL du logo de l'organisation.
   */
  logoUrl?: string;

  /**
   * Nom de l'organisation.
   */
  nom?: string;

  /**
   * Pays de l'organisation.
   */
  pays?: string;

  /**
   * Problèmes que l'organisation cherche à résoudre.
   */
  problemesResoudre?: string;

  /**
   * Secteur d'activité de l'organisation.
   */
  secteur?: string;

  /**
   * Taille de l'organisation.
   */
  taille?: string;

  /**
   * Vision stratégique de l'organisation.
   */
  vision?: string;
}
