/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTechComponentDto {

  /**
   * Description du composant technologique
   */
  description?: string;

  /**
   * Nom du composant technologique
   */
  nom?: string;

  /**
   * Position horizontale sur le canevas
   */
  positionX?: number;

  /**
   * Position verticale sur le canevas
   */
  positionY?: number;

  /**
   * Statut du composant technologique
   */
  statut?: 'AS_IS' | 'TO_BE' | 'LES_DEUX';

  /**
   * Type du composant technologique
   */
  type?: 'SERVEUR' | 'RESEAU' | 'CLOUD' | 'BASE_DE_DONNEES' | 'MIDDLEWARE' | 'ORDINATEUR_PORTABLE' | 'ROUTEUR_RESEAU' | 'CAPTEUR_IOT_CONSOMMATION' | 'SMARTPHONE_PROFESSIONNEL' | 'STOCKAGE_NAS' | 'BASE_DE_DONNEES_POSTGRESQL' | 'SERVEUR_APPLICATIONS' | 'API_REST' | 'LOGICIEL_CYBERSECURITE' | 'SYSTEME_EXPLOITATION_LINUX' | 'PLATEFORME_CLOUD' | 'PARE_FEU' | 'SWITCH' | 'VPN' | 'CONNEXION_INTERNET_FIBRE' | 'AUTRE';
}
