/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateBpmnElementDto {

  /**
   * Declencheur de l'evenement, applicable si l'element est un evenement
   */
  declencheur?: 'MESSAGE' | 'MINUTERIE' | 'ERREUR' | 'SIGNAL' | 'CONDITIONNEL' | 'TERMINAISON' | 'ESCALADE';

  /**
   * Nom de l'element BPMN
   */
  nom?: string;

  /**
   * Position horizontale de l'element sur le canevas
   */
  positionX?: number;

  /**
   * Position verticale de l'element sur le canevas
   */
  positionY?: number;

  /**
   * Statut d'avancement de l'element
   */
  statut?: 'AS_IS' | 'TO_BE' | 'LES_DEUX';

  /**
   * Type de l'element BPMN
   */
  type?: 'EVENEMENT_DEBUT' | 'EVENEMENT_FIN' | 'EVENEMENT_INTERMEDIAIRE' | 'TACHE' | 'PASSERELLE_EXCLUSIVE' | 'PASSERELLE_PARALLELE' | 'PASSERELLE_INCLUSIVE' | 'PASSERELLE_EVENEMENTIELLE' | 'SOUS_PROCESSUS';

  /**
   * Type de tache, applicable si l'element est une tache
   */
  typeTache?: 'UTILISATEUR' | 'SERVICE' | 'MANUELLE' | 'ENVOI' | 'RECEPTION' | 'REGLE_METIER' | 'SCRIPT';
}
