/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateChangementDto {

  /**
   * Description de la demande de changement
   */
  description?: string;

  /**
   * Statut de la demande de changement
   */
  statut?: 'PROPOSE' | 'APPROUVE' | 'REJETE' | 'IMPLEMENTE';

  /**
   * Titre de la demande de changement
   */
  titre?: string;
}
