/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateBpmnProcessusDto {

  /**
   * Contenu XML du diagramme BPMN
   */
  bpmnXml?: string;

  /**
   * Description du processus BPMN
   */
  description?: string;

  /**
   * Nom du processus BPMN
   */
  nom?: string;

  /**
   * Type du processus BPMN
   */
  type?: 'METIER' | 'SUPPORT' | 'PILOTAGE';
}
