/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UrbanisationVueEntity {

  /**
   * Nombre d'applications représentées.
   */
  applicationCount: number;

  /**
   * Contenu SVG du diagramme.
   */
  svg: string;

  /**
   * Nombre de zones d'urbanisation représentées.
   */
  zoneCount: number;
}
