/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VisionCanvasEntity {

  /**
   * Objectifs métier visés par le produit.
   */
  businessGoals?: string | null;

  /**
   * Canaux de distribution ou de communication.
   */
  channels?: string | null;

  /**
   * Concurrents identifiés.
   */
  competitors?: string | null;

  /**
   * Facteurs de coût associés.
   */
  costFactors?: string | null;

  /**
   * Identifiant du vision canvas.
   */
  id: string;

  /**
   * Besoins adressés par le produit.
   */
  needs?: string | null;

  /**
   * Identifiant de l'organisation propriétaire.
   */
  organisationId: string;

  /**
   * Description du produit.
   */
  product?: string | null;

  /**
   * Sources de revenus envisagées.
   */
  revenueStreams?: string | null;

  /**
   * Groupe cible du produit.
   */
  targetGroup?: string | null;

  /**
   * Date de dernière mise à jour.
   */
  updatedAt: string;
}
