/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ZoneApplicationRefEntity } from '../models/zone-application-ref-entity';
export interface ZoneApplicationEntity {

  /**
   * Application affectée à la zone.
   */
  application: ZoneApplicationRefEntity;

  /**
   * Identifiant de l'application.
   */
  applicationId: string;

  /**
   * Identifiant de la zone.
   */
  zoneId: string;
}
