/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ZoneApplicationEntity } from '../models/zone-application-entity';
import { ZoneCountEntity } from '../models/zone-count-entity';
import { ZoneParentRefEntity } from '../models/zone-parent-ref-entity';
export interface ZoneUrbanisationEntity {

  /**
   * Compteurs des relations de la zone.
   */
  '_count'?: ZoneCountEntity;

  /**
   * Applications affectées à la zone.
   */
  applications?: Array<ZoneApplicationEntity>;

  /**
   * Date de création de la zone.
   */
  createdAt: string;

  /**
   * Sous-zones (enfants directs) de la zone dans la hiérarchie Zone > Quartier > Îlot.
   */
  enfants?: Array<ZoneUrbanisationEntity>;

  /**
   * Identifiant de la zone d'urbanisation.
   */
  id: string;

  /**
   * Nom de la zone d'urbanisation.
   */
  nom: string;

  /**
   * Identifiant de l'organisation propriétaire de la zone.
   */
  organisationId: string;

  /**
   * Zone parente, si la zone n'est pas une racine.
   */
  parent?: (ZoneParentRefEntity & {
}) | null;

  /**
   * Identifiant de la zone parente.
   */
  parentId?: string | null;

  /**
   * Type de la zone d'urbanisation.
   */
  type: 'ZONE' | 'QUARTIER' | 'ILOT';

  /**
   * Date de dernière modification de la zone.
   */
  updatedAt: string;
}
