/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ZoneParentRefEntity {

  /**
   * Identifiant de la zone parente.
   */
  id: string;

  /**
   * Nom de la zone parente.
   */
  nom: string;

  /**
   * Type de la zone parente.
   */
  type: 'ZONE' | 'QUARTIER' | 'ILOT';
}
